### ISSUE TITLE
add replay behavior for the Debugger.paused event for CDP Proxy

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#1018]
@hediet We can add replay behavior for the Debugger.paused event here: https://github.com/microsoft/vscode-js-debug/blob/9a4ed83bb2293b499f4b5f3b189826711fcba8a1/src/adapter/cdpProxy.ts#L152-L162

_Originally posted by @connor4312 in https://github.com/microsoft/vscode-js-debug/issues/893#issuecomment-853107732_

**Comment by hediet** [comment]
I don't fully understand the replay logic.

`CdpProxyProvider` is only constructed when the proxy is requested.
But the `CdpProxyProvider` also manages the replays.
This means that events that are emitted before the proxy has been requested are not replayed, right? (I guess `Debugger.paused` is usually emitted before an extension has a chance to request a CDP proxy, when the debug session breaks on start)

Also, any `Debugger.paused` or `Debugger.resumed` event should clear all previously sent events of this type.

**Comment by connor4312** [comment]
Ah, true. For CSS it's fine since js-debug core never requests the CSS domain so there cannot be anything to replay before the CDP process is connected.

Instead of instantiating the proxy provider on demand here, we could store it in a private property so that it gets set up and listens as soon as the session is created

https://github.com/microsoft/vscode-js-debug/blob/14323d3edd2c9e8097494e440bf33e3c16a5f2df/src/adapter/debugAdapter.ts#L444

**Comment by hediet** [comment]
I think the server can (and should) still be spawned on demand. Maybe the replay logic can be put into a service that is created with each debug session?

And maybe there should be a limit of how many events are kept in memory.

**Comment by connor4312** [comment]
The server won't actually get spawned until `proxy()` is called for the first time.

For the Debugger domain, there will be either 0 or 1 events stored, since we will only need to replay the `Debugger.paused()` event. A consumer might want want us to replay scriptParsed events, but I would rather avoid this since they can be _very_ noisy for some applications.

**Comment by hediet** [comment]
>  since we will only need to replay the Debugger.paused() event.

We should always replay either `Debugger.resumed` or `Debugger.paused`, otherwise the absence of `Debugger.paused` event is not noticeable without hacks.

> The server won't actually get spawned until proxy() is called for the first time.

Oh right.

**Comment by connor4312** [comment]
The behavior in Chrome, when calling `Debugger.enable()` is to assume the target is not paused _unless_ a `paused` event is received before the response to `Debugger.enable()` is returned. This pattern is also used for other domains, and that's how the "replayed" events are sent in the current code. So we only need to replay Debugger.paused, and if we see a resume then clear the last paused event.

> I think for this case it would be nice if JS Debug has some hook to reliably connect to the CDP proxy before the debugger session is started.

Yea. We could expose some extension API for this

**Comment by connor4312** [comment]
@hediet can you verify this one?
