### ISSUE TITLE
Issue setting breakpoint in Lerna monorepo child modules

### ISSUE THREAD

**Issue by ntotten** [microsoft/vscode-js-debug#1050]
**Describe the bug**
In a monorepo configured with Lerna, breakpoints on the main repo that I am debugging get hit, but the dependency repos are skipped.

**To Reproduce**
Video here: https://www.youtube.com/watch?v=Bln3lQE36Fw

The full minimal repro is published here: https://github.com/ntotten/lerna-ts-debug-repro

**Log File**
[vscode-debugadapter-9e0f457f.json.gz](https://github.com/microsoft/vscode-js-debug/files/6750207/vscode-debugadapter-9e0f457f.json.gz)

**VS Code Version:** Version: 1.57.1 (Universal)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z (2 wks ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

**Comment by connor4312** [comment]
Apologies for the delayed response. This is happening because you're precompiling the code and then bundling it again with webpack, and webpack by default doesn't "follow" the originally generated sourcemaps. However, you can use the [source-map-loader](https://webpack.js.org/loaders/source-map-loader/) to make it do so 🙂
