### ISSUE TITLE
Missing intellisense for sourceMapRenames

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode-js-debug#1053]
Testing https://github.com/microsoft/vscode-js-debug/issues/1033

**Is your feature request related to a problem? Please describe.**
I tried adding in `sourceMapRenames` and noticed that it wasn't a suggested option. I also typed in `"false"` instead of `false` by accident at first, since there wasn't a suggestion to press tab on.

**Describe the feature you'd like**
I'd like Intellisense to be added for the `sourceMapRenames` key.

**Comment by connor4312** [comment]
This is not readily possible today since we don't know what names are actually relevant in the current scope. Js-debug makes a guess if you type identifiers that have a rename, but it automatically falls back if they're undefined in the current scope.

It would be possible to find relevant renames if we did source code analysis on the project, but this has the potential to be expensive, especially for large minified bundles.

**Comment by rzhao271** [comment]
The issue seems to be fixed now. I am able to add that key in a config in `launch.json`.
