### ISSUE TITLE
Breakpoints should display the column the debugger is currently on

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-js-debug#106]
1. Set and hit a line breakpoint

![image](https://user-images.githubusercontent.com/2230985/69197543-88acc000-0ae6-11ea-8df5-1651dd9da6e8.png)

2. Click the first column breakpoint on the line, then immediately:

![image](https://user-images.githubusercontent.com/2230985/69197493-5ac77b80-0ae6-11ea-9406-f62b42612c43.png)

The second image should be the state immediately after hitting the BP.

This is a cosmetic issue, not high pri

**Comment by roblourens** [comment]
I think this would be a vscode issue, @isidorn

**Comment by connor4312** [comment]
This behavior is correct (second case) with the existing node debugger, so it might be something that PWA is doing wrong--or at least differently.

**Comment by connor4312** [comment]
Thinking about it more, I believe it's something PWA is doing differently that exposes a bug in vscode. I think there should never be a case where we're on a line with a breakpoint where there isn't an active red dot painted.

However, this does work correctly with the existing node debugger, so it's precipitated by something PWA does differently.

**Comment by isidorn** [comment]
The issue here is that the line breakpoint is probably moved by the node debug adapter to the correct column, and this is not done by the pwa debugger.
VS Code does not render the breakpoint since there is no breakpoint there, and that is expected bheavior.
However please note that this is a bug which I will look into github.com/microsoft/vscode/issues/85148

**Comment by connor4312** [comment]
This was fixed with changes in vscode.
