### ISSUE TITLE
Functionality clarification on debugging node_modules code

### ISSUE THREAD

**Issue by AntonOfTheWoods** [microsoft/vscode-js-debug#1071]
It is a little unclear to me whether this is supported or not, so I can't tell if it is not supported, a config error or a bug. By doing my best monkey-randomly-hitting keyboard I managed to get my TS/React project debugging and stepping through the code after struggling with unbound breakpoints. However, the issue I am having is with an import from node_modules. The package I would like to step through (https://github.com/d-i-t-a/R2D2BC) was originally written in TS but when installed from npm has minified js, maps and types. 

When I try and step into the node_models code, it steps into the minified file, offers to pretty print but ignores the present and referenced map, and while it does pretty print the code, the yellow line representing the current line being executed doesn't move from the first line of the file (though it flickers when stepping, giving me the impression it is stepping but that it still thinks all the code is on line one). 

I am on Ubuntu 20.04 and get the same issue when trying to debug a Chrome or Edge (dev) launch profile. I tried lots of different options containing the string "map" in the config but a lot of them simply meant the breakpoints weren't bound at all.

Should I be able to step through this code with help from the map, or am I trying to do something impossible?

**Comment by connor4312** [comment]
You can configure the `outFiles` to include that package in your node_modules, e.g setting it to `['${workspaceFolder}/**/*.js', '!**/node_modules/**', '${workspaceFolder}/node_modules/@d-i-t-a/reader/**/*.js']`. By default node_modules are ignored since parsing sourcemaps for all modules can be time+cpu intensive and is unnecessary 99% of the time.

> though it flickers when stepping, giving me the impression it is stepping but that it still thinks all the code is on line one

This is usually a result of multiple statements or expressions being on the same line. You can see the current column based on where the yellow indicator is within the line.

**Comment by connor4312** [comment]
Oh, sorry, that applies to Node projects. With React which I'm guessing entails webpack, you only need the source-map-loader to have webpack follow the sourcemaps when it bundles the files: https://webpack.js.org/loaders/source-map-loader/

**Comment by AntonOfTheWoods** [comment]
Thanks for your reply @connor4312 . Unfortunately, I am not sure I understand. Are you saying that you are sure it is supported and that there is no bug, so it is a problem with my configuration? I use `create-react-app` (react-scripts) which hides these details but does use webpack underneath. My understanding is that it is already doing what you are suggesting I should configure.

There are maps everywhere (both in my build directory and the node_modules directory next to the js files) but nothing I do convinces VSCode to use the map to show me what is being executed. Again, in my project-internal TS code, it is working fine and stepping over the TS code in my files.

If it just pretty-printed the module code and then stepped on the correct line then I could (probably) work out what was being executed but it does not. The current line of execution stays on line 1. 

If you are sure this definitely works, do you have any suggestions on other places to find info about how to fix my config?

**Comment by connor4312** [comment]
> There are maps everywhere (both in my build directory and the node_modules directory next to the js files) but nothing I do convinces VSCode to use the map to show me what is being executed

This is a webpack thing. Your own code works because it's generating saurcemap during the compilation process, which Webpack knows about, but without the loader it doesn't know about existing sourcemaps.

It looks like react-scripts [recently](https://github.com/facebook/create-react-app/commit/382ba21052ffd1321f3e7bb1dcb70d442106dff1) added the source-map-loader which will fix this, though it does not (yet) seem present in any published version. You could either `react-scripts eject` the config to make the changes yourself, or wait until that happens. Or if you just need it for some local testing, you could always manually edit `node_modules/react-scripts/config/webpack.config.js` to add that in.

**Comment by AntonOfTheWoods** [comment]
Thanks very much for that @connor4312 ! It is now clear. I tried the hack you suggested but it looks like code might only be compatible with the new, webpack 5-compatible create-react-app (I get errors building with the change). They have just released an alpha version so I will give that a crack. Thanks again!
