### ISSUE TITLE
Random ports appear when exiting debug mode

### ISSUE THREAD

**Issue by khkh-ms** [microsoft/vscode-js-debug#1092]
**Describe the bug**
When exiting a JavaScript Debug session from the debug bar, 1 port turns into 3 with two being seemingly random ports.

**To Reproduce**
1. Open https://github.com/chrisdias/gh-static-e2e with Remote-Container or GitHub Codespaces
2. Create new JavaScript Debug Terminal
3. Run npm run server
4. Disconnect debugger from debug bar

Expected behavior
The debugger is disconnected, but all other UI remains the same.

What happens instead
The debugger is disconnected, but two seemingly random ports are added in the "Ports" view. These go away when the actual terminal process that started the debugger is killed.

**VS Code Version:** 1.59.1

**Additional context**
![image](https://user-images.githubusercontent.com/64149947/131400109-4fd1b002-f257-4052-89f2-01197059adac.png)

**Comment by alexr00** [comment]
@connor4312 It looks like this is what's happening:
1. Javascript debugger terminal is started
2. Extension returns port attributes that indicate that the processes associated with the debugger terminal should be ignored.
3. Once the debugger is disconnected from the terminal, the extension stops saying the terminal processes should be ignored.

Would you consider continuing to return `Ignore` for processes related to JS debug terminals?

**Comment by connor4312** [comment]
I'm not sure what I want to do here. When you detach from the process but leave it running, js-debug no longer knows about the lifecycle of the process and cannot authoritatively return whether a port is a "debug port".

What triggers the editor to check for port attributes again? VS Code knows the process ID is unchanged, is it expected that port attributes might change for existing `(pid, port)` pairs?

**Comment by alexr00** [comment]
Hmm, I assumed since JS Debug contributed the terminal profile it would consider all terminals created with that profile to belong to JS Debug in a way, but it sounds like this isn't how terminal profiles work.

VS Code checks for port numbers every couple seconds on a timer and we check for attributes any time there's a change there. We could do the `(pid, port)` check in VS Code, but attributes  can change for based on UI interactions from the user and based on settings changes, though I don't expect those things happen often.

**Comment by connor4312** [comment]
>  it would consider all terminals created with that profile to belong to JS Debug in a way

This is what happens, but given an incoming port/pid we don't know whether that belongs to one of our terminals. We only check to see if we know it because of a debug session, which isn't the case if the user detaches the debugger but leaves the program running.

I'll add a pid/port cache in js-debug to mitigate this.

**Comment by alexr00** [comment]
Thank you!
