### ISSUE TITLE
Running multiple debug sessions opens about:blank instead of correct URL

### ISSUE THREAD

**Issue by Bird-mw** [microsoft/vscode-js-debug#1097]
**Describe the bug**
Previously on the old debugger I could run multiple debug sessions towards the same webRoot. This no longer works and results in first a warning `It looks like a browser is already running from an old debug session. Please close it before trying to debug, otherwise VS Code may not be able to connect to it. Debug anyway?` Pressing debug anyway correctly opens a new tab but it does not inject the correct URL but about:blank. Manually entering the URL in the window correctly loads the session and breakpoints work correctly.

Checking the log file it encounters two errors:
```Command failed: C:\WINDOWS\System32\taskkill.exe /F /T /PID 34796 ERROR: The process "34796" not found. ```
```Error: Unable to attach to browser at h.prepareLaunch at runMicrotasks```

**To Reproduce**
Using this launch.json
```{
    "name": "Task 1",
    "type": "chrome",
    "request": "launch",
    "url": "file://${workspaceFolder}/debug.html?app=clientApp:task1",
    "sourceMaps": true,
    "webRoot": "${workspaceFolder}",
    "skipFiles": [
        "*.dll.js"
    ],
    "smartStep": true
},
{
    "name": "Task 2",
    "type": "chrome",
    "request": "launch",
    "url": "file://${workspaceFolder}/debug.html?app=clientApp:task2",
    "sourceMaps": true,
    "webRoot": "${workspaceFolder}",
    "skipFiles": [
        "*.dll.js"
    ],
    "smartStep": true,
    "trace": true
}

```

**Log File**

[vscode-debugadapter-e84a537d.json.gz](https://github.com/microsoft/vscode-js-debug/files/7103627/vscode-debugadapter-e84a537d.json.gz)

**VS Code Version:** 1.60

**Comment by connor4312** [comment]
Yea, that warning is there for a reason, "debugging anyway" is not likely to work 🙂 

The easy solution is to specify two different `userDataDir`s so two separate instances of Chrome are launched. But this is not a great experience. Alternately, you can specify the `port` when launching since that'll allow multiple debug sessions to connect. However, the new debugger attaches to all tabs of debugged browsers by default, so you'll end with duplicate sessions. Probably the best way is to just open a separate tab for each URL you want to debug in the browser.
