### ISSUE TITLE
ts-jest (and maybe ts-node) files do not get source mapped when debugging.

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode-js-debug#1100]
**Describe the bug**

When we updated to 1.60 today, we noticed that we couldn't set breakpoints our tests anymore, or if they worked, they'd be on the wrong line, and anything we browsed was the unmapped code (not the original TS source).

**To Reproduce**

I have created a self-contained reproducer here: https://github.com/jakebailey/ts-jest-vsc-repro

**Log File**

[vscode-debugadapter-2d0009e1.json.gz](https://github.com/microsoft/vscode-js-debug/files/7108661/vscode-debugadapter-2d0009e1.json.gz)

**VS Code Version:** 1.60

**Additional context**

**Comment by connor4312** [comment]
Thanks for the issue and repro!

This is due to logic that we added to help with monorepos, where we default to resolving sourcemaps in the nearest package.json-containing directory relative to the program. In this case that meant we only resolve sourcemaps in `node_modules/jest`.

This'll be fixed in Monday's [nightly debugger build](https://github.com/microsoft/vscode-js-debug#nightly-extension). You can also explicitly set `outFiles` to its default value in your launch.json:

```
            "outFiles": [
                "${workspaceFolder}/**/*.js",
                "!**/node_modules/**"
            ]
```

**Comment by jakebailey** [comment]
Given this regressed VSC 1.60 (which just came out), will this be backported or anything?

**Comment by connor4312** [comment]
Yes I think I will introduce this as a candidate for 1.60.1.

**Comment by sandy081** [comment]
Changed to August 2021 recovery milestone so that we can track it from our queries.

**Comment by uk20931085** [comment]
pain in arse
