### ISSUE TITLE
Is it possible to run the debug terminal outside of VSCode?

### ISSUE THREAD

**Issue by jmcdo29** [microsoft/vscode-js-debug#1101]
I know this may seem like a bit of an odd request, but I haven't found anything on t yet. I love the ability to just run a JS debug terminal from the integrated terminal, it's been incredibly helpful recently! In my normal workflow I like to use `tmux` to set up multiple terminals and usually keep the extra screen space when working with VSCode by not using the integrated terminal. So I was wondering if there's a way I can have VSCode open and run the debug terminal from inside my tmux configuration, starting the debug terminal outside of VSCoe, but still getting the auto attaching to work. 

I understand if this isn't possible, but just wanted to reach out and see if I was missing something. Great work on the functionality!

**Comment by connor4312** [comment]
The debug terminal works by setting environment variables, so 'technically yes'. The tricky thing is that in order to capture a debug session, js-debug listens on a unix socket or Windows pipe file, which is created for each window (auto attach is just a slightly specialized version of this mechanism). Maybe you can create a terminal in VS Code and then "pop out" that terminal's environment variables to a tmux session.

If you wanted to write a simple extension for this, the APIs you need are in place. For example you can call `vscode.commands.executeCommand('extension.js-debug.createDebuggerTerminal', '<some command to run>')` to create a debug terminal, or if you use auto attach just use the existing terminal APIs to create one and send a command to it.

**Comment by acheronfail** [comment]
FWIW I did a similar thing where I just spawned an instance of my terminal emulator from within the js-debug terminal. Since it was created as a child all the env passed through, and it automatically attached when I ran `node`, etc.
