### ISSUE TITLE
Breakpoints become unbound in VScode on Mac.

### ISSUE THREAD

**Issue by Thomalexa** [microsoft/vscode-js-debug#1126]
**Describe the bug**
I have a nodejs application that I use VScode for on a Mac. I go into any portion of the application and set breakpoints for debugging.  After launching the debugger, the breakpoints become unbound and debugging doesn't hit the points and allow for step-throughs.

**To Reproduce**
1. Open any js file, create a breakpoint.
2. NPM start to start the server. 
3. Run the debugger.

Attempt to use the application to a point where the debugger should hit your breakpoint. Nothing happens.

Latest VSCode V1.61

**Comment by connor4312** [comment]
Please collect a log file using the instructions in the issue template

**Comment by regstar** [comment]
Hello everyone.

I have a similar problem with my debugger configuration. I started my debug session for my angular application with the following steps:

1. Set the auto attachment to smart
2. Open a JavaScript Debug Console
3. run "npm start" on the JS Console
4. Node debugger attached automatically
5. Wait for compiling and some other stuff
6. Click on "localhost:4200" link to open chrome for debugging
7. Debugger attached to chrome
Described here: https://github.com/microsoft/vscode-js-debug

So in my settings there is no lauch.json existing, because I understand it like so, that I does not need this anymore, because of the new attachment mechanism.

But, when I want to set a breakpoint in VSCode, I get an "unbound gray breakpoint". So when I use a breakpoint on my chrome, it will read this and opened in my attached debugger.

Do I miss something? I use IntelliJ and want to try VSCode to debug some solutions. On IntelliJ it is easy to attach the debugger because you need only start the application, and click on the link with ctrl + cmd and it's done. Sounds like the new VSCode debugger is working.

My setup:
MacOS 11.6
Chrome  95.0.4638.69
VSCode Version: 1.61.2
Build in JS Debugger attached to node and my localhost app

Cheers

**Comment by connor4312** [comment]
Please collect a log file using the instrutions posted above.

**Comment by Thomalexa** [comment]
For what it's worth, I saw another post where another developer experienced the same issue. They eventually reimaged their Mac and the issue was resolved.

I have yet to reimage my machine, but that's my next step.

Thomas



________________________________

**Comment by regstar** [comment]
@connor4312 I dont use the launch.json method. I only attach my debugger directly. Because of the:
"In js-debug we aim to provide rich debugging for modern applications, with no or minimal configuration required. Here are a few new features that js-debug brings"

Is there a other way to get the logs?

**Comment by connor4312** [comment]
Most likely your setup needs additional configuration which will require a launch.json
