### ISSUE TITLE
Can not debug VSCode project

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-js-debug#115]
macOS catalina, VSCode insiders,  VS Code JavaScript Debugger (Nightly) Version: 2019.11.28323

1. Open vscode repository
2. Change the launch.json to use pwa-chrome and pwa-node
3. Try to debug vscode by running one of the following launch configurations: "Launch VS Code", "Debug VS Code, Main, Renderer and Extensino Host"
4. Notice the error after a timeout

Please note that debugging a simple Javascript program works just fine and debugging vscode extensinos also seems to work

![Screenshot 2019-11-21 at 15 54 47](https://user-images.githubusercontent.com/1926584/69349153-96457f80-0c77-11ea-841e-8cf4c3062d29.png)

**Comment by connor4312** [comment]
Thanks for the issue! I'm having some trouble trying to repro on my end on Mojave. After launching VS code--I'm assuming the debugged editor opens up--can you visit http://localhost:9222/json/version? That error indicates that the extension couldn't reach that endpoint, which is where the debugee should publish metadata to.

**Comment by isidorn** [comment]
Appologies, I had a wrong setup.

Now I see some different issues:
Launch VS Code works just fine (just takes like 5 s for the other window to be ready)
1. However the Attach To Extension Host fails with

```
Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:5870).
```

2. Stopping Launch VS Code does not close the other Renderer window which got opened

Also I can visit and it works http://localhost:9222/json/version

**Comment by connor4312** [comment]
Okay, thanks! 

 1. Didn't test that yet, I'll take a look!
 2. Fixed in https://github.com/microsoft/vscode-pwa/pull/116, should be in the next nightly

**Comment by isidorn** [comment]
Great, thanks. I'll try it again tomorrow.

**Comment by connor4312** [comment]
Debugging ongoing with Isidor in Slack. Attaching to extension host works for me, we'll continue investigation tomorrow.

**Comment by robnov** [comment]
Hi all, I'm getting the same issue, here's my launch.json:

![image](https://user-images.githubusercontent.com/8605335/70530605-62d78000-1ba7-11ea-86b2-1da794389124.png)


For reference, here's what happens when I access http://localhost:9225/json/list in the debugger session.

It closes after ~10s with the message "Unable to launch browser: "Lookup cancelled": timeout after 10000ms".

————————

Tested on Insiders:

Version: 1.41.0-insider
Commit: bef029a9d21904c0085c4e8ef1335d9c33a28fa4
Date: 2019-12-09T15:40:24.842Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

————————

Also tested on stable VS Code:

Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

**Comment by connor4312** [comment]
@robnov that's a separate issue, but regardless fixed in d9532f1, you'll get it in the next nightly build (8AM PST daily) 🙂

**Comment by robnov** [comment]
Legend!

**Comment by connor4312** [comment]
I haven't heard any other reports of this, let me know if it's still an issue!
