### ISSUE TITLE
Can't find Node.js binary "node" using nvm

### ISSUE THREAD

**Issue by tipy01** [microsoft/vscode-js-debug#1150]
**Describe the bug**

I got in the trace:

"Can't find Node.js binary "node": path does not exist. Make sure Node.js is installed and in your PATH, or set the "runtimeExecutable" in your launch.json"

when I run such configuration:
```JSON
{
    "name": "test",
    "request": "launch",
    "type": "node",
    "program": "${workspaceFolder}/index.js",
    "trace": true
}
```

I use nvm to manage my node install, and the PATH env is set, so I do not want to use runtimeExecutable nor runtimeVersion or anything else that will link to a specific node version. I want to keep using the latest version of node and this managed via nvm only. Just for info, if I set runtimeExecutable or runtimeVersion it launch OK.

If I launch the js script manually in the vscode terminal it launch OK (it finds the node binary).

**VS Code Version:** 
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-91-generic

JavaScript Debugger (Nightly)
v2021.11.1217
(the problem is seen also on standard version of JavaScript Debugger)

nvm: 0.39.0

```bash
env
NVM_INC=/home/username/.nvm/versions/node/v16.13.1/include/node
NVM_DIR=/home/username/.nvm
NVM_CD_FLAGS=
NVM_BIN=/home/username/.nvm/versions/node/v16.13.1/bin
PATH=/home/username/.nvm/versions/node/v16.13.1/bin:/home/username/.cargo/bin:/home/username/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
The terminal is bash.

**Comment by connor4312** [comment]
This means that the PATH environment variable is not being set in a way that VS Code can inherit it. Ensure that NVM is set up in your .bashrc file or .zshrc file, as appropriate. If you launch VS Code via the `code` CLI, then make sure the command line environment where it's launched from has the appropriate version in its PATH.

**Comment by tipy01** [comment]
Hi @connor4312 , thank your for your answer.

Yes NVM is set as appropriate in .bashrc file [like described here](https://github.com/nvm-sh/nvm#manual-install).
I do not launch VS Code via the `code` CLI.

If I just launch `node index.js` in the VS Code terminal it launch well (it inherits the PATH).

I want to know what is the right way to set the PATH environment variable for VS Code (especially the vscode-js-debug extension) to inherit it?

**Comment by adamchenwei** [comment]
We also started having this EXACT same issue. Why? We has proper nvm config in our bashrc file. SO that's not the problem. Any idea why it happens? How can we help to provide more issue tracing?
My VS Code Info

```
Version: 1.58.0 (Universal)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z (5 mos ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0
```

**Comment by adamchenwei** [comment]
This ticket should not be closed. @tipy01  its too premature to do so.

**Comment by tipy01** [comment]
Actually, in my case the problem was when  ["vscode-testcafe" extension calls vscode.debug.startDebugging](https://github.com/romanresh/vscode-testcafe/blob/5c734c02cd1fb711949ef9795589d94d6ccd3b74/src/extension.ts#L338)

The basic example in first post was just to illustrate.

What is weird is that if I launch VS Code via the code CLI (typing `code` in a bash shell) I do not have the problem. I will use that solution as a workaround.


@adamchenwei , for me removing launch.json have no effect.

**Comment by adamchenwei** [comment]
@tipy01 make sure also restart. and if its an extension. may want to remove or disable all extension and try again

**Comment by connor4312** [comment]
@adamchenwei you're also on a 6 month old version of vscode that doesn't have the fix in this issue

**Comment by centur** [comment]
I'm started to get this error too, on the latest VSCode @ macosx with M1:

```
code --version
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
arm64
```

Symptoms are the same:
- Intergrated terminal has  correct path, nvm is working, node binary is there etc.
  - I also have `"terminal.integrated.inheritEnv": true,` but this seems have no effect on js-debug extension in any way

-  JS debugger can't attach, because node is not in PATH - `We did not find node on your PATH, so we cannot enable auto-attach in your environment`.
 - In developer tools of VSCode `process.env.PATH` looks wrong: `process.env.PATH - '/usr/bin:/bin:/usr/sbin:/sbin'`
 - Setting up `debug.javascript.defaultRuntimeExecutable: {}` and pointing it to a node biinary also does not help.
 - Interesting that this error happens even when `"debug.javascript.autoAttachFilter": "disabled"`. 





Error message stack trace if this helps :
```
onDidChangeNotification | @ | workbench.desktop.main.js:802
-- | -- | --
  | (anonymous) | @ | workbench.desktop.main.js:802
  | invoke | @ | workbench.desktop.main.js:67
  | deliver | @ | workbench.desktop.main.js:67
  | fire | @ | workbench.desktop.main.js:67
  | addNotification | @ | workbench.desktop.main.js:802
  | notify | @ | workbench.desktop.main.js:1988
  | (anonymous) | @ | workbench.desktop.main.js:1724
  | _showMessage | @ | workbench.desktop.main.js:1724
  | $showMessage | @ | workbench.desktop.main.js:1724
  | _doInvokeHandler | @ | workbench.desktop.main.js:1731
  | _invokeHandler | @ | workbench.desktop.main.js:1731
  | _receiveRequest | @ | workbench.desktop.main.js:1731
  | _receiveOneMessage | @ | workbench.desktop.main.js:1731
  | (anonymous) | @ | workbench.desktop.main.js:1731
  | invoke | @ | workbench.desktop.main.js:67
  | deliver | @ | workbench.desktop.main.js:67
  | fire | @ | workbench.desktop.main.js:67
  | fire | @ | workbench.desktop.main.js:83
  | _receiveMessage | @ | workbench.desktop.main.js:83
  | (anonymous) | @ | workbench.desktop.main.js:83
  | invoke | @ | workbench.desktop.main.js:67
  | deliver | @ | workbench.desktop.main.js:67
  | fire | @ | workbench.desktop.main.js:67
  | acceptChunk | @ | workbench.desktop.main.js:83
  | (anonymous) | @ | workbench.desktop.main.js:83
  | L | @ | workbench.desktop.main.js:3181
  | emit | @ | node:events:390
  | addChunk | @ | node:internal/streams/readable:315
  | readableAddChunk | @ | node:internal/streams/readable:289
  | Show 2 more frames
```

**Comment by gaston-23** [comment]
> I'm started to get this error too, on the latest VSCode @ macosx with M1:
> 
> ```
> code --version
> 1.68.1
> 30d9c6cd9483b2cc586687151bcbcd635f373630
> arm64
> ```
> 
> Symptoms are the same:
> 
> * Intergrated terminal has  correct path, nvm is working, node binary is there etc.
>   
>   * I also have `"terminal.integrated.inheritEnv": true,` but this seems have no effect on js-debug extension in any way
> * JS debugger can't attach, because node is not in PATH - `We did not find node on your PATH, so we cannot enable auto-attach in your environment`.
> * In developer tools of VSCode `process.env.PATH` looks wrong: `process.env.PATH - '/usr/bin:/bin:/usr/sbin:/sbin'`
> * Setting up `debug.javascript.defaultRuntimeExecutable: {}` and pointing it to a node biinary also does not help.
> * Interesting that this error happens even when `"debug.javascript.autoAttachFilter": "disabled"`.
> 
> Error message stack trace if this helps :
> 
> ```
> onDidChangeNotification | @ | workbench.desktop.main.js:802
> -- | -- | --
>   | (anonymous) | @ | workbench.desktop.main.js:802
>   | invoke | @ | workbench.desktop.main.js:67
>   | deliver | @ | workbench.desktop.main.js:67
>   | fire | @ | workbench.desktop.main.js:67
>   | addNotification | @ | workbench.desktop.main.js:802
>   | notify | @ | workbench.desktop.main.js:1988
>   | (anonymous) | @ | workbench.desktop.main.js:1724
>   | _showMessage | @ | workbench.desktop.main.js:1724
>   | $showMessage | @ | workbench.desktop.main.js:1724
>   | _doInvokeHandler | @ | workbench.desktop.main.js:1731
>   | _invokeHandler | @ | workbench.desktop.main.js:1731
>   | _receiveRequest | @ | workbench.desktop.main.js:1731
>   | _receiveOneMessage | @ | workbench.desktop.main.js:1731
>   | (anonymous) | @ | workbench.desktop.main.js:1731
>   | invoke | @ | workbench.desktop.main.js:67
>   | deliver | @ | workbench.desktop.main.js:67
>   | fire | @ | workbench.desktop.main.js:67
>   | fire | @ | workbench.desktop.main.js:83
>   | _receiveMessage | @ | workbench.desktop.main.js:83
>   | (anonymous) | @ | workbench.desktop.main.js:83
>   | invoke | @ | workbench.desktop.main.js:67
>   | deliver | @ | workbench.desktop.main.js:67
>   | fire | @ | workbench.desktop.main.js:67
>   | acceptChunk | @ | workbench.desktop.main.js:83
>   | (anonymous) | @ | workbench.desktop.main.js:83
>   | L | @ | workbench.desktop.main.js:3181
>   | emit | @ | node:events:390
>   | addChunk | @ | node:internal/streams/readable:315
>   | readableAddChunk | @ | node:internal/streams/readable:289
>   | Show 2 more frames
> ```

in my case, I had the same issue with the process.env.PATH and i fixed adding to settings.json
"debug.javascript.defaultRuntimeExecutable": {
        "pwa-node": "/path/to/.nvm/versions/node/vX.X.X/bin/node"
    },

**Comment by hanspoo** [comment]
In my case with linux the problem was that i use nvm for multiple node versions, and nvm is configured in .bashrc, so it worked when i started vscode from a bash terminal, but didn't when using the kde launcher (that obvioously is not using bash at all), so i launch vscode from the terminal, tried to automate, i'll check latter.

**Comment by DustinPham** [comment]
I'm seeing this issue as well which I think is the same thing:
![image](https://user-images.githubusercontent.com/5573129/206290979-7a70dfda-e79f-45cd-8ad6-602ece8ef8ec.png)

**Comment by alexey2baranov** [comment]
why this ticket closed? Not sure opening program through the terminal command is a good solution

**Comment by alexey2baranov** [comment]
also this workaround not works if vscode installed from flatpack.  and later runned by the following command

>  /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=code --file-forwarding com.visualstudio.code

**Comment by alexey2baranov** [comment]
installing from snap works out ot the box

**Comment by kendall-powerchord** [comment]
I am having this problem on mac, and it is because the default shell is zsh and I like to use bash.  My bash is fully configured, but I neglect the configuration of zsh.

This caused the strange situation of the terminal inside vscode being able to use nvm and node, but debug in vscode was having the same errors I would get if I used zsh for a terminal.  I put the "~/.profile" config I had been building for bash in "~/.zshrc" and things started to work correctly in vscode debug.  My theory is because vscode is started and loads configuration from zsh in the background, because macOS doesn't respect my choice of terminal.

I'm writing an electron app, so I had to figure out something because normally I just set "runtimeExecutable" in the .vscode/launch.json, pointing it at my node location using nvm, and called it a day, but electron requires being able to access node, and use the "runtimeExecutable" pointed at the location of electron within the node_modules folder in the project.

I hope this helps someone.

**Comment by matiux** [comment]
> In my case with linux the problem was that i use nvm for multiple node versions, and nvm is configured in .bashrc, so it worked when i started vscode from a bash terminal, but didn't when using the kde launcher (that obvioously is not using bash at all), so i launch vscode from the terminal, tried to automate, i'll check latter.

I'm in the same situation on Linux Arch. Using nvm, I have to run vscode from terminal (zsh)

**Comment by henricazottes** [comment]
For me it's super flaky.

I've tried several options given here:
- removed launch.json
- added `defaultRuntimeExecutable` to settings.json
- and finally adding `engines` to package.json

Suddenly it started working (debugger was attaching node processes) so I removed one by one my modifications to see which one had fixed it. I ended up in my initial configuration with a working debugger and nothing changed from when it wasn't working 🤔 Probably I missed something but don't know what.

I'm on a mac M1

**Comment by piotr-kwiatkowski** [comment]
Same issue here. 

I'm using zsh and in my case, I had to remove 2 lines from the `.bash_profile`:
```bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
```
(And I don't recall adding those lines there manually)

After restarting VSCode everything worked fine.

**Comment by hanspoo** [comment]
Those lines where added when you installed node versión manager: nvm, some
way or another you did it... copy paste may be.

**Comment by jeremycharron** [comment]
If you're using WSL and have a similar issue : 

Make sure you install the [WSL extension in VSCode][1].

Then, restart VSCode by running the following command at your project root in a WSL Terminal : 

    code .

Node debugging should work properly.

  [1]: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

**Comment by richard-stafflink** [comment]
I feel like there are a lot of red-herrings and border line wive's tales.

I use Linux and bash is my default terminal. And I used NVM.

The issue was that I hadn't set `default` for NVM, once I fixed that, it wasn't until I restarted VSCode that all was fixed.
NOTE: "Developer: Reload Window" does NOT work.
NOTE: Adding `-i` to my bash args only fixed half the issue (red-herring), and was not necessary, only the VSCode restart.

**Comment by ackzell** [comment]
[Setting a default](https://github.com/nvm-sh/nvm?tab=readme-ov-file#set-default-node-version) on `nvm` did it for me on a Mac too, thanks!

**Comment by katlim-br** [comment]
In my case, this was because I installed NVM using homebrew, and they discourage it. NVM prefers using their instructions.

Then they instruct you to add some commands to the bashrc (this was also part of my problem because I added those to bash_profile, but when Node runs a debug process it is a non-interactive bash session).

And then it worked.
