### ISSUE TITLE
runtimeArg being dropped

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/vscode-js-debug#1165]
**Describe the bug**
Using the attached launch.json which specifies 

"--inspect-brk=5858",

When the run is launched the arg is missing and we get the command line:

> /mnt/wsl/projects/git/www/electron-react-pos/node_modules/.bin/electron --preserve-symlinks --preserve-symlinks-main -r ts-node/register/transpile-only --remote-debugging-port=9223 ./src/main/main.ts --debug -info --config config.json --results results/myresults

**To Reproduce**
Use the attached launch.json 

**Log File**

log file is also in the attached zip file
-->

**VS Code Version:** 

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000
[launchFile.zip](https://github.com/microsoft/vscode-js-debug/files/7800333/launchFile.zip)

**Additional context**

**Comment by connor4312** [comment]
`--inspect-brk` is normally dropped since it's not generally necessary due to the way the JS debugger attaches to the program. However, if you need to preserve it, you can do so by specifying `attachSimplePort: 5858` which will instruct the debugger to keep the `--inspect` argument and attach via that port instead of its ordinary file socket.

**Comment by mwoodpatrick** [comment]
Many thanks for the prompt reply much appreciated. Adding attachSimplePort: 5858 did fix my problem but was required for me to debug my electron app, so if debugging of electron apps on WSL-2 is supposed to work without it then there does appear to be a bug here if debugging of electron apps on WSL-2 is not supposed to work without it then I think this property needs to be documented better. Either way I think this bug should be reopened until we have a resolution on this.

**Comment by connor4312** [comment]
Ah yea, it looks like Electron does detection in WSL and actually launches `electron.exe`, which is launched on the Windows side and thus isn't able to connect back to the js-debug debug port. Specifically, this _requires_ that you `npm install` on the windows side and then run in WSL, otherwise you won't get the `.exe` version. Not sure what/if there's something we should do here. I dislike adding a special case for "Electron in WSL2 where it's npm installed on windows."

**Comment by mwoodpatrick** [comment]
FWIW all of my runs currently are purely on wsl-2 I'm running electron as a Linux process not electron.exe as a windows process

**Comment by connor4312** [comment]
You can use the `attachSimplePort: 5858` property in your launch.json for this case. If that's present, the runtimeArg will not be dropped.
