### ISSUE TITLE
Out of order output console messages 

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#122]
- https://github.com/microsoft/vscode-gdpr-tooling
- Clone https://github.com/microsoft/vscode-gdpr-tooling
- Run the tests launch config with no breakpoints
- Sometimes the last message comes in the wrong order, maybe race btw async handling of error vs not-error messages

![image](https://user-images.githubusercontent.com/323878/69598279-b0f05f00-0fbd-11ea-853a-094eca2c4b1b.png)

**Comment by connor4312** [comment]
TIL about a new event. We print that on child process' `exit`, which might happen before stdio is flushed. Instead we should wait for [`close`](https://nodejs.org/api/child_process.html#child_process_event_close).

We also shouldn't dump our stderr unless the process terminates with a non-zero exit code.

**Comment by connor4312** [comment]
This is somewhat complicated and I'm not sure what the correct solution is. Here's what's happening:

 1. CDP tells PWA that a console API was called.
 2. PWA tells VS Code that the console API was called, and gives it a variable reference it can use to expand more info.
 3. The subprocess exits and PWA sends output with a string indicating as much to VS Code.
 4. VS Code asks for the variables referenced in the console log
 5. PWA gives them back and the console line is printed

Gist for the tool https://gist.githubusercontent.com/connor4312/02aa59291e8823b9fcdc2a52c36e6f09/raw/c5bd78015b9b9804e3f2c11bb20893213040b16b/log.json -> https://microsoft.github.io/vscode-pwa-analyzer/index.html

I think the most correct thing to do here is for VS Code to reorder/buffer console lines and display them in the order that they were received, rather than in the order that variables were requested.

**Comment by roblourens** [comment]
@isidorn

**Comment by isidorn** [comment]
Might be related https://github.com/microsoft/vscode/pull/81403
@connor4312 feel free to jump on that PR

**Comment by connor4312** [comment]
I touched up that PR, but it appears to be separate from this. I'll look into it some more and create a separate PR or add a fix to Dmitry's, depending on complexity.

**Comment by connor4312** [comment]
I'm going to combine this with https://github.com/microsoft/vscode-js-debug/issues/161. If/when that works, this will too.
