### ISSUE TITLE
Custom visualizer function throws error

### ISSUE THREAD

**Issue by FrozenKiwi** [microsoft/vscode-js-debug#1221]
**Describe the bug**
After upgrading to the latest, my `customDescriptionGenerator` throws errors when visualizing arrays.

**To Reproduce**

Create a new project
1. Add simple file with an array:
```
const v = [
    123,
    456,
    789
]

console.log(v);
```
2. Create Node.js debug config in `launch.json`  & set custom visualizer: 
```
          "customDescriptionGenerator": "function (def) { if (this.toString) { const _v = this.toString(); if (_v.indexOf(\"[object Object]\") < 0) return _v; } return def; }",
```
(it also seems to happen on simpler function calls, but not straight `this.toString()` calls

3. Debug file, put breakpoint on console.log, expand `v`
`Error processing variables: TypeError: (0 , p.localize) is not a function`

 ```
Error processing variables: TypeError: (0 , p.localize) is not a function
	at R.getCustomObjectDescription ([...]() VS Code\resources\app\extensions\ms-vscode.js-debug\src\extension.js:2:952479)

**Log File**

I tried this, but didn't see any log file output
<!--
If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.

⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

-->

**VS Code Version:**
Version: 1.65.2 (user setup)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:55.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Additional context**
Add any other context about the problem here.

**Comment by Allon-Guralnek** [comment]
It seems this bug was fixed in extension v1.68.0 which has been released to the marketplace, but my VSCode has v1.67.2 which still suffers from this issue. I couldn't find an option to manually update the extension (probably can't since it's a "built-in" extension) so I had to switch to the nightly build to resolve it. I used the instructions [here] to do that(https://github.com/microsoft/vscode-js-debug#nightly-extension), and in addition restarted VSCode (otherwise it wouldn't use the newly installed nightly build). Problem solved! Will have to remember to return to the main build next version.
