### ISSUE TITLE
Feature Request: Show toString of Objects In Hover

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#1284]
It would be really helpful if the hover title would show the `.toString()` result of the object:

![image](https://user-images.githubusercontent.com/2931520/170229476-50703c24-1527-438e-b798-442ace66762d.png)

In this case, `.toString()` of the range would be `[3,3)`.

v8 allows you to call a function (such as `.toString()`) but throw before any side-effect is caused.

**Comment by connor4312** [comment]
My instinct would be to use `toString()` in place of where we currently show `{ startLineNumber: 3, lineCount: 0 }`. This is the same code that runs to show the preview in the **VARIABLES** view, too.

The difficult part is that we build that preview off of the information we get by calling `getProperties` on the scope (or the parent object -- both are "runtime objects"), which looks like this for an instance of a class that implements `toString()`

```json
{
  "type": "object",
  "className": "Foo",
  "description": "Foo",
  "objectId": "-4497892529713776404.1.30",
  "preview": {
    "type": "object",
    "description": "Foo",
    "overflow": false,
    "properties": [
      {
        "name": "hello",
        "type": "string",
        "value": "world"
      }
    ]
  }
}
```

Unfortunately there's no indication that there is a `toString()` there (since it's on the prototype of that object. So, we'd have to actually evaluate code separately to determine what the preview should be. If we do this in a scope where there's a ton of variables, that's a ton of extra evaluations we make.

While I'm not enthused about introducing discrepancy between display in the hover and variables view, we could special case the hover evaluation to do something special -- would that still be useful?

**Comment by hediet** [comment]
> would that still be useful?

Yes, but having it everywhere would be even more useful.

**Comment by connor4312** [comment]
@hediet I think you can verify

**Comment by hediet** [comment]
Use it almost daily. A great feature!!

**Comment by liuxilu** [comment]
NOT a debugging viewer WITHOUT this function!!!
It's long-requested in fact, but people hardly find the repo of a built-in/shipped-with function other than vscode's where such issue will be said 'go to the debugger repo!'
Microsoft/vscode#26234 Microsoft/vscode#38273
