### ISSUE TITLE
After setting hexadecimal display in a number, if you set a value, the value that you type is considered decimal

### ISSUE THREAD

**Issue by thaystg** [microsoft/vscode-js-debug#1310]
And should be considered hexadecimal or at least support 0x(ffffff), to say that it's an hexadecimal value.

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode-js-debug/issues/1231#issuecomment-1115445355

**Comment by thaystg** [comment]
Pinging @gregg-miskelly as he asked me to test it :)

**Comment by connor4312** [comment]
I'm also open to DAP proposals that would allow hex input to be specified. In that case we'd probably solve the ambiguity I mentioned by just saying that the output type is the same as the input type. But currently there's not a way to express this in the protocol.

**Comment by gregg-miskelly** [comment]
My suggestion to solve this: include `0x` (or whatever is the appropriate way to express that a number is hexadecimal in the source language) on value so that it is clear when it is round tripped that this is a hexadecimal number.

This is how the .NET and C++ debuggers solve the problem in Visual Studio.

**Comment by connor4312** [comment]
If you use `0x` to set a number, that will already work since JavaScript supports that. However, the client will need to send it, since js-debug doesn't "know" that the user was looking at a hex representation of the variable when `setExpression` gets called.

js-debug also returns hex representation of strings and bigints when requested, for which 0x doesn't signal sufficiently.

**Comment by gregg-miskelly** [comment]
There are two ways that this gets solved in Visual Studio.

For trivial types, such as integers, the .NET/C++ debuggers use `ValueFormat.hex` to know that the client wants the value in hex, and then will return `0x10` instead of either `10` or `16`.

For non-trivial types, like presumably your bigint example, or like a pointer to a string in C++, the way this works is that VS we ask the debugger backend for an "editable" value for the string. We don't currently have a way of supporting this in DAP, though it feels natural to do this as a "ValueFormat".
