### ISSUE TITLE
Documentation: property `trace`

### ISSUE THREAD

**Issue by SlickNutter** [microsoft/vscode-js-debug#1367]
The description of the `trace` property is not helpful.

While going through the documentation of the [chrome-launch debugger](https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md#trace-1) I found the property `trace`.
The description says: `Configures what diagnostic output is produced.`

While looking for further into the code, I found [this](https://github.com/microsoft/vscode-js-debug/blob/f32c8d5f72c9199e8c0d1346d9225e3ed18e97af/src/targets/browser/browserLauncher.ts#L122):
`dumpio: typeof trace === 'boolean' ? trace : 

> trace.stdio,`

This allowed me to find the following [website](https://deno.land/x/puppeteer_plus@0.12.0/vendor/puppeteer/website/versioned_docs/version-9.1.1/puppeteer.launchoptions.dumpio.md?code=), which states:

> If true, pipes the browser process stdout and stderr to process.stdout and process.stderr.

Further searching [inside the repository revealed](https://raw.githubusercontent.com/microsoft/vscode-js-debug/2994e0576d17a54e11132f92945039dd827e0d78/.github/ISSUE_TEMPLATE/bug_report.md):

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.

Is this property purely for traces related to vscode-js-debug?
Could the description be improved, for example by mentioning the [properties that can be passed to this option](https://github.com/microsoft/vscode-js-debug/blob/2344223485d1a9cf3476f12a57a0bf38bcf2e204/src/build/strings.ts#L14) when it is set to be an object?

**Comment by connor4312** [comment]
The JSON schema of the launch configuration is the most comprehensive source of documentation for individual options.

When writing an object, for instance, the logFile property has a description: 

<img width="306" alt="image" src="https://user-images.githubusercontent.com/2230985/194398143-8c2b79d7-1194-4819-99fc-79535babc96a.png">

For most cases, just setting it to true is sufficient. I may eventually remove the option of having it as an object, since I never have needed that for any diagnostic work.
