### ISSUE TITLE
Can't attach to process

### ISSUE THREAD

**Issue by llotall** [microsoft/vscode-js-debug#1402]
I have Angular 14 apps, that's works with proxy server of .net application on 5001 port.
I trying attach to opened tab by the follow launch settings:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "attach",
      "name": "Launch Chrome (existing)",
      "url": "https://localhost:5001",
      "webRoot": "${workspaceRoot}",
      "port": 9222,
      "trace": true
    }
  ]
}
```
Chrome browser has a set in target path launch flag  --remote-debugging-port=9222
Project opened in the root of web app folder 
![image](https://user-images.githubusercontent.com/18103301/192780445-a65e8a79-d1da-4cf1-85fe-1300d34e9aee.png)

seems that all is made correct, but this is doesn't work.

In trace file i have next errors:

```
  "tag": "runtime.launch",
  "timestamp": 1664367221968,
  "message": "Error looking up /json/version",
  "metadata": {
    "ok": false,
    "body": "connect ECONNREFUSED 127.0.0.1:9222",
    "statusCode": 503,
    "url": "http://127.0.0.1:9222/json/version",
    "error": {
      "message": "Unexpected 503 response from http://127.0.0.1:9222/json/version: connect ECONNREFUSED 127.0.0.1:9222",
      "stack": "Error: Unexpected 503 response from http://127.0.0.1:9222/json/version: connect ECONNREFUSED 127.0.0.1:9222\n\tat b.requestHttp
    }
  },
  "level": 0

and

"tag": "runtime.launch",
  "timestamp": 1664367225575,
  "message": "Launch returned error",
  "metadata": {
    "error": {
      "message": "Cannot connect to the target at localhost:9222: Could not connect to debug target at http://localhost:9222: Could not find any debuggable target",
      "stack": "Error: Cannot connect to the target at localhost:9222: Could not connect to debug target at http://localhost:9222: Could not find any debuggable target\n\tat S.acquireConnectionForBrowser
    },
    "wasCancelled": true,
    "name": "S"
  },
  "level": 2
```

**VS Code Version:** 1.71.2

**Comment by connor4312** [comment]
The error you're receiving indicates that the browser is not listening on port 9222.

Usually this is because, while you run something like `chrome --remote-debugging-port=9222` in your terminal, Chrome is already running. Only new instances of Chrome can be started in debug mode. You either want to ensure all other instances are completely closed, or run using a separate user data dir like `--remote-debugging-port=9222 --user-data-dir=some-other-profile` so that you get a new instance of the main process.

Let me know whether that fixes it for you.
