### ISSUE TITLE
TypeScript dependency breakpoints not hit when using JavaScript Debug Terminal

### ISSUE THREAD

**Issue by icholy** [microsoft/vscode-js-debug#1403]
**Describe the bug**

I have a typescript library which I'm publishing with sourcemaps, but breakpoints in the `.ts` files are not hit when invoked from the JavaScript Debug Terminal.

**To Reproduce**

I've created a stand-alone repo here: https://github.com/icholy/typescript_breakpoint_bug

1. `npm i`. 
2. Open vscode and set breakpoint at `node_modules/@icholy/no-ts-breakpoint-bug/src/index.ts:3`.
3. Open Javascript Debug Terminal and run `node main.js`.

**Log File:** Not sure how to do this with the JavaScript Debug Terminal.

**VS Code Version:** 1.71.2

**Additional Notes**:

* If you `npm link` the package, the breakpoints work.
* If you use a launch config, the breakpoints work.

**Comment by connor4312** [comment]
This requires creating a launch.json and configuring the outFiles. Please see documentation here: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery

**Comment by icholy** [comment]
@connor4312 Is there any way of changing the default `outFiles` that the Debug Terminal uses?

**Comment by connor4312** [comment]
Yep, you can also set the `debug.javascript.terminalOptions` in your user or workspace settings.

> If this is default behavior, why isn't it finding the source maps?

Your case is having a breakpoint at `node_modules/@icholy/no-ts-breakpoint-bug/src/index.ts:3`. Because it's in `node_modules`, this is excluded by default. Note that you probably want to only add node modules you want to set breakpoints in rather than removing the `!**/node_modules/**` negation entirely, for performance reasons.

**Comment by icholy** [comment]
@connor4312 That worked, thank you! However, when it hits the breakpoint, it goes to the js file. Is that expected behaviour?

**Comment by connor4312** [comment]
Hm, it's not. I will look at this next week..

**Comment by icholy** [comment]
I've pushed my workspace configuration to the linked repo.
