### ISSUE TITLE
What is the difference between "resolveSourceMapLocations" and "outFiles"?

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/vscode-js-debug#1452]
Feels like the purpose of both property is to tell the files should be source mapped.

**Comment by connor4312** [comment]
The `outFiles` are scanned before debugging is started in order to set breakpoints in them before starting the program (to avoid missing locations that are hit early). `resolveSourceMapLocations` defaults to the outfiles, but it can be changed or unset to allow the debugger to resolve sourcemaps at runtime that may be elsewhere on the machine.
