### ISSUE TITLE
Stacks in debug console do not linkify filenames

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode-js-debug#1523]
on macOS ventura, using Angular 12.

See screenshot.

![Screenshot 2023-01-19 at 10 16 01 pm](https://user-images.githubusercontent.com/9585787/213480163-6e5c5e5e-0bb0-46fd-8f1b-2e9bca422ec1.png)

The filenames don't have a `file://` before them, or provide any way for the Debug Console to recognise them as filenames.

**Comment by connor4312** [comment]
Please collect logs using the instructions in the issue template.

**Comment by jpike88** [comment]
[vscode-debugadapter-72d6e1b9.json.gz](https://github.com/microsoft/vscode-js-debug/files/10458447/vscode-debugadapter-72d6e1b9.json.gz)

This is using a different error stack but same basic problem
![Screenshot 2023-01-19 at 11 09 53 pm](https://user-images.githubusercontent.com/9585787/213493501-b31a84b2-fab6-430f-b20e-389a8c120c7e.png)

**Comment by connor4312** [comment]
This is because your paths contain `webpack:/` which I think makes the link detector not pick them up, since their location is not valid. I'm curious what build setup/config you have. It looks like your `sourceRoot` is set to `"webpack:///"` and then ordinary(?) relative paths for each source url within that, which I've not seen before; that's causing the default sourceMapPathOverrides not to match. Normally webpack doesn't have a sourceRoot and just emits sources with URIs like `webpack:///foo/bar.js`

**Comment by jpike88** [comment]
I'm using `ng serve` from the angular cli

**Comment by connor4312** [comment]
Could you share the version you're running, and anything you have in your `angular.json`?

**Comment by jpike88** [comment]
angular 15.1.1

attached is zip containing 
[angular.json.zip](https://github.com/microsoft/vscode-js-debug/files/10543216/angular.json.zip)
angular.json

**Comment by connor4312** [comment]
Thanks. It looks like you have manually configured sourceMapPathOverrides that only apply to `webpack:///./src`, so things in node_modules don't get mapped.

Instead of overriding the default sourceMapPathOverrides, you probably just want to set your `webRoot` to `${workspaceFolder}/client`
