### ISSUE TITLE
Pretty print for debugging does not work

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode-js-debug#1539]
![Code_-_Insiders_2UVdKmcJcY](https://user-images.githubusercontent.com/2931520/216040344-5641cf0c-4330-4252-b845-28ae810c86d7.gif)

It triggers the error:

```
ERR Source not found: CodeExpectedError: Source not found
    at a.P (vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44734)
    at vscode-file://vscode-app/c:/Users/hdieterichs/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:890:44228
```

**Comment by connor4312** [comment]
This actually does work, the error is from the "worker" process where the script isn't loaded.

If you're paused in a script that gets pretty-printed, the debugger sends a fake resume and pause with the new, pretty file location. However, in this case, you were not paused. A pretty script is available and would be stepped into the next time you were paused in the source, but there's not API for an extension to otherwise reopen the source and show you it's available...

To reduce confusion I will make this action only available when the debugger is stopped.

**Comment by hediet** [comment]
But how would I set a breakpoint in that script?

**Comment by connor4312** [comment]
True, I've opened a feature request for the API we'd need to do this properly: https://github.com/microsoft/vscode/issues/173057
