### ISSUE TITLE
Cannot debug Angular library linked to an angular app

### ISSUE THREAD

**Issue by twilker** [microsoft/vscode-js-debug#1823]
**Describe the bug**
I have a standard Angular 16 library and application in two different workspaces / repositories. I link the build library using `npm link` to the application and start it. I would expect to be able to debug the library sources from the application as ` Go To Definition` is working fine. But it is not - see below

**To Reproduce**
Steps to reproduce the first issue:
1. Clone the minimal [app](https://github.com/twilker/vs-debug-angular-app) and [library](https://github.com/twilker/vs-debug-angular-library)
2. In the library project execute
```
npm i
npm run build
cd ./dist/library
npm link
```
3. In the app project execute
```
npm i
npm link library
```
4. Set breakpoint in app.component.ts L12
5. Start Debugging (F5)
6. Step Into -> leads to library.mjs although a source map exists for this file which would lead to the .ts source file
![mjs-not-resolved](https://github.com/microsoft/vscode-js-debug/assets/2802526/2e357dfe-a6e6-4d41-8998-dcabf74171c8)

**Log File**

1. Issue (.mjs not resolved)
[vscode-debugadapter-e4aa047e.json.gz](https://github.com/microsoft/vscode-js-debug/files/12737615/vscode-debugadapter-e4aa047e.json.gz)

**VS Code Version:** 
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by connor4312** [comment]
You'll want to use the [`source-map-loader`](https://webpack.js.org/loaders/source-map-loader/) in the webpack config for the app so that webpack will follow the original sourcemap.

I also noticed and tried their esbuild loader, which does [support nested sourcemaps](https://github.com/evanw/esbuild/commit/23f0884de58781d04b6300cccec732f4e6ac8eac) out of the box, but something in how it's called in the Angular CLI seems to make that not work as it should.
