### ISSUE TITLE
Could not read http://127.0.0.1:8080/fibonacci.c

### ISSUE THREAD

**Issue by hackwaly** [microsoft/vscode-js-debug#1836]
**Describe the bug**
I followed the instructions there https://github.com/microsoft/vscode/issues/194071. But I can't see source content of `fibonacci.c` in loaded scripts. `*.js` and `*.html` have no problem.

**To Reproduce**
See https://github.com/microsoft/vscode/issues/194071

**Log File**

**VS Code Version:** 
Version: 1.84.0-insider (Universal)
Commit: 874831ebcf088f59735879156f62308ce48f17d1
Date: 2023-10-06T19:18:47.163Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Additional context**
<img width="1334" alt="image" src="https://github.com/microsoft/vscode-js-debug/assets/540298/c797d152-62e7-47ba-809b-e0a971e8ce24">

**Comment by connor4312** [comment]
Ensure your workspaceFolder / webRoot is set up correctly. DWARF symbols do not include the original sources content, so if your paths are not set up correctly, that is the message you will get.

Collecting a log file using the instructions in the issue template will allow me to see where the problem is.
