### ISSUE TITLE
Attaching to a remote EH process actually debugs the parent server process

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#1914]
- Connect to an ssh remote
- Start this debug config
```
{
    "name": "Attach by Process ID",
    "processId": "${command:PickProcess}",
    "request": "attach",
    "skipFiles": [
        "<node_internals>/**"
    ],
    "type": "node"
}
```
- Pick the pid of the extension host, or one of its children
- Check `process.pid` in the debug console to see that you got attached to the server process instead
- Also, setting
```
"attachExistingChildren": true,
"autoAttachChildProcesses": true,
```

doesn't make a difference

**Comment by roblourens** [comment]
Context: https://github.com/microsoft/vscode-remote-release/wiki/Profiling-Remote-Processes

**Comment by fellotin** [comment]
> * Conéctese a un control remoto ssh
> * Inicie esta configuración de depuración
> 
> ```
> {
>     "name": "Attach by Process ID",
>     "processId": "${command:PickProcess}",
>     "request": "attach",
>     "skipFiles": [
>         "<node_internals>/**"
>     ],
>     "type": "node"
> }
> ```
> 
> * Elija el pid del host de la extensión o uno de sus hijos
> * Verifique `process.pid`en la consola de depuración para ver si se adjuntó al proceso del servidor.
> * Además, estableciendo
> 
> ```
> "attachExistingChildren": true,
> "autoAttachChildProcesses": true,
> ```
> 
> no hace la diferencia

**Comment by connor4312** [comment]
I cannot reproduce this. But note that putting a process in debug mode involves sending a SIGUSR1 signal to the process which causes it to listen on 9229. If something else was already listening on that port for any reason, that will be connected to instead of the desired process. Would that explain what you were seeing? / was the server process already listening on 9229 prior to running that command?

**Comment by connor4312** [comment]
Let me know if you have more info / think there's an underlying issue here
