### ISSUE TITLE
Breakpoint on first line jumps to next line

### ISSUE THREAD

**Issue by jcrben** [microsoft/vscode-js-debug#204]
In https://gitlab.com/jcrben-repro/vscode-debugging-repro/tree/break-on-first-line I'm finding that if I set a breakpoint on the first line and run the [`node launch file`](https://gitlab.com/jcrben-repro/vscode-debugging-repro/blob/aba03e081a505348f080c14f4a8c788867601d1a/.vscode/launch.json) task, the breakpoint jumps to the next line and stop there instead of the first line. I also set `disableOptimisticBPS` altho it doesn't seem like it should matter for a `.js` file.

This happens in either `script.js` or `script.ts`. I can break on the first line if I set `stopOnEntry` to true.

I noticed https://github.com/microsoft/vscode-js-debug/pull/61 which might be related.

I've got issues with breakpoints firing on invisible breakpoints or stepping in when I'm trying to step over, but in browsing these issues it seems like these are probably largely upstream.

**Comment by connor4312** [comment]
Thanks for the issue!

It looks like the core issue is that [we assume](https://github.com/microsoft/vscode-js-debug/blob/842b32f90c54313e922719795f0ea1c286189b08/src/targets/node/nodeTarget.ts#L106) a hardcoded offset in the first line of the script by 62 chars. This is a thing up to Node 8, but in Node 10 it seems like the first line offset is removed entirely.

In the v1 Node adapter, we [assumed](https://github.com/microsoft/vscode-node-debug/blob/47747454bc6e8c9e48d8091eddbb7ffb54a19bbe/src/node/nodeDebug.ts#L1920-L1922) the same thing. In v2, we call `getPossibleBreakpoints` over CDP and set the breakpoint at the next possible location, which works.

While the latter is probably the more correct solution, this is different than what we do today and I'm unsure how well it would interact with in-place transpiled scripts. Since it seems like modern versions of Node have removed this offset, I would prefer to simply drop it, which would remove complexity from the adapter as well. 

cc @roblourens

**Comment by connor4312** [comment]
> I've got issues with breakpoints firing on invisible breakpoints or stepping in when I'm trying to step over, but in browsing these issues it seems like these are probably largely upstream.

If you're using ts-node, we don't support that quite yet, though it should be in soon https://github.com/microsoft/vscode-js-debug/pull/174

**Comment by jcrben** [comment]
Might be a ts-node thing, but at least one case happened in v2 and not in v3. The code is kinda complicated with lots of decorators, may create a repro later.

**Comment by connor4312** [comment]
Should be fixed in tomorrow's daily build. Please reopen this issue if not!
