### ISSUE TITLE
Should it debug typescript files ?

### ISSUE THREAD

**Issue by DaniGTA** [microsoft/vscode-js-debug#214]
I try too debug my jest test's but its writen in typescript and with this js debugger it didnt run.
Just stays with 2,9mb ram in the taskmanager and didnt say debugger atteched.

Without this extension the default debugger works. (no changes at the launch config)

Current launch config:
```

        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "runtimeArgs": [
                "--inspect-brk",
                "${workspaceRoot}/node_modules/jest/bin/jest.js",
                "-i",
                "--runInBand"
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
            "port": 9229
        }
```

**Comment by connor4312** [comment]
It should. `--inspect-brk` may be messing with things--I think with that we might get paused 'invisibly' on the entrypoint. Try removing that and seeing it it solves things.

I think it'd be sensible to strip --inspect-brk from args if we see it, and instead used it to flip on our managed `stopOnEntry` flag.

If that doesn't solve it, could you share a repo containing your setup so that I could give it a spin?

**Comment by DaniGTA** [comment]
With `--inspect` i have the same problem.

Here is the repo with the problem: https://github.com/DaniGTA/listManager just start "Debug Jest Tests"

**Comment by connor4312** [comment]
Thanks for adding me!

Adjusting your launch config to remove the --inspect flags makes it work--this new debugger boots into inspect mode a little different, and --inspect interferes with that. I think adding a change in this extension to strip out manually-added --inspect flags is appropriate.

Also, fun fact, you no longer need to `--runInBand` with this adapter, we can automatically attach to and debug in all spawned children 🙂 However right now workers where BPs get hit can run a little slower

This launch config should work for you. There are two further issues that will be fixed in tonight's 5PM PST build:

 1. You couldn't previously use `pauseForSourceMap: false` for transpiled code. We also default pauseForSourceMap to false for Node code, since it will run off disk and we don't need the instrumentation BP which slows things down significantly in the few cases (like Jest) where it can be turned on.
 2. Jest will sometimes break in unexpected locations

 
```
        {
            "name": "Debug Jest Tests",
            "type": "pwa-node",
            "request": "launch",
            "trace": true,
            "runtimeArgs": [
                "${workspaceRoot}/node_modules/jest/bin/jest.js",
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen",
        }
```

**Comment by DaniGTA** [comment]
I'm glad the bug was found. 👍

**Comment by markfinlabs** [comment]
FYI I just opened an issue related to Jest having noticed this thread and testing for myself: https://github.com/microsoft/vscode-js-debug/issues/222

**Comment by connor4312** [comment]
Easiest way to verify:

 1. `npx create-react-app my-app`
 2. Set a breakpoint in App.test.js
 3. Hit the debug code lens in the package.json and run tests

**Comment by alexr00** [comment]
Verified this bug, but the package.json code lens left out the `npm` part of `npm react-scripts test` and just tried to run `react-scripts test`.
