### ISSUE TITLE
Step into worker broken on macOS

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#223]
- Debug the web-worker-ts demo
- Break on the `new Worker` line, press step in
- It doesn't break in the worker

Works on linux. This is why `cross thread constructor source map` is failing on mac.

On Linux there is an extra Debugger.paused event fired before the worker is loaded, which has the `asyncCallStackTraceId` that we need to pause when the worker is loaded. This isn't sent on mac. Chrome bug right, or do you see anything else?

[ww-mac.txt](https://github.com/microsoft/vscode-js-debug/files/4051124/ww-mac.txt)
[ww-linux.txt](https://github.com/microsoft/vscode-js-debug/files/4051125/ww-linux.txt)

**Comment by connor4312** [comment]
Actually, it is breaking. But it looks like we depend on [`asyncCallStackTraceId`](https://chromedevtools.github.io/devtools-protocol/tot/Debugger#event-paused) in order to know whether the next pause is related to a previous async step, which is present on Linux and Windows but marked deprecated and removed in OSX. Looking into the proper alternative, docs are sparse.

**Comment by connor4312** [comment]
I looked through it a bit. It doesn't seem like there were any public announcements or discussion on the deprecation. I have some ideas for alternative approaches, but I was mostly just throwing things and seeing what works. I pinged Dmitry to see if he has any recommendations.

**Comment by roblourens** [comment]
One thing I noticed is that in Chrome, we get a pause event of type "other", and vscode is getting  type "instrumentation". I got rid of the code that sets the beforeScriptWithSourceMapExecution instrumentation breakpoint, and then it works.

**Comment by connor4312** [comment]
That's because with an instrumentation breakpoint, we wan to continue evaluation if the user hasn't also requested to break at this location in some way. Because Chrome on OSX is missing the async call stack behavior, the adapter doesn't forecast that the user expects a break at the entrypoint of the webworker, so it continues onwards.

**Comment by connor4312** [comment]
Chatting with @dgozman:

>Connor Peet
>    One kind of ugly idea I had was to stack the last call frame we saw before stepping in, and then looking for that frame in the async stack of pause events to see if we got here from an async step.
>
>​Dmitry Gozman
>    I see the problem, let me think a bit
>
> Dmitry Gozman
>    Your solution seems ok for now, but I'd suggest to compare all call frames up to asyncStackTraceId to be on the safe side.
>
> Dmitry Gozman
>    The right fix would be to change v8 to emit "ambiguous" pause reason with both "instrumentation" and "asyncStep". I can do that soon-ish, but it will take time to reach stable Chrome version

This scenario is an edge case, and the call frame implementation would add a moderate amount of complexity to an already fairly complex scenario. Additionally, there is a workaround to manually set a breakpoint on the first line of the worker file. Therefore I would prefer to leave this as-is awaiting the upstream fix, unless we get user feedback that this is problematic for them.

**Comment by roblourens** [comment]
That's fine with me. Debugging workers at all is totally new so we aren't losing anything.
