### ISSUE TITLE
Warning when starting extension debugging with pwa- prefix

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-js-debug#272]
Testing https://github.com/microsoft/vscode/issues/89393 on Windows

The first time I ran the launch config for extension debugging I got this warning in the Extension Development window that opened. That is the only window I saw the warning in.

"[c:\Users\alros\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.38943]: Overwriting extension c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\ms-vscode.js-debug-nightly with c:\Users\alros\.vscode-insiders\extensions\ms-vscode.js-debug-nightly-2020.1.38943."

**Comment by connor4312** [comment]
I think this may be because for one version of insiders we used `latest` as the version number of the built-in extension `js-debug-nightly`. This seems to have caused an assortment of negative side effects, this may be one. This has since been fixed, I'll close the issue unless it appears to be persistent.
