### ISSUE TITLE
Log lines lost after first debug session

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#299]
I guess I haven't noticed this before but maybe you are aware of it. On the second and later debug sessions, we lose messages from the debug log because we call `logger.setup` a second time but the logger is not "reset" to queue messages after the first session.

Also need to think about how it works when two sessions run simultaneously.

**Comment by connor4312** [comment]
I'm currently refactoring services a bit (so that we can reuse the breakpoint predictor in #291). Generally the idea is that there'll be a service factory at the top level, whose `.child` can be access (+disposed) of, which basically lets you build a tree of services for the session. Mightly help in reconciling the logger story.
