### ISSUE TITLE
Issues with invalid hit count bp

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#300]
- Set a hit count bp with invalid hit count
- In the same file, set a normal bp
- The hit count bp is moved to the line of the normal bp but we do hit the normal bp as expected, seems like they are getting switched around

![image](https://user-images.githubusercontent.com/323878/73800256-0179fa80-476d-11ea-9f8a-786228d5ca9f.png)

![image](https://user-images.githubusercontent.com/323878/73800297-1eaec900-476d-11ea-9c60-6803dce85090.png)

![image](https://user-images.githubusercontent.com/323878/73800273-10f94380-476d-11ea-85b5-4efa7d79d8d9.png)

[vscode-debugadapter.json.txt](https://github.com/microsoft/vscode-js-debug/files/4156866/vscode-debugadapter.json.txt)

**Comment by connor4312** [comment]
This is because when we fail to parse a hit condition, we simply skip the given breakpoint. If the breakpoint is first in the list, this causes the editor to think that the breakpoint we resolved at the given location was the hit count breakpoint. 

![image](https://user-images.githubusercontent.com/2230985/73889508-b7545000-4824-11ea-8b7d-5c4a24453730.png)

We already show a message in the console when we can't parse it, so I think the correct behavior here would be to keep the breakpoint around as unverified.
