### ISSUE TITLE
Separate extension install needed for latest VSCode (1.42) &  Insiders (>1.43.insiders)

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode-js-debug#315]
According to the update docs (https://code.visualstudio.com/updates/v1_42#_new-javascript-debugger) it seems this extension is now built in to VSCode. Does this extension need to be install separately? (Does it co-exist, so as to have the latest/greatest features/fixes?)

Is the "old" "Debugger for Chrome" extension still needed?

**Comment by connor4312** [comment]
The extension is built-in on VS Code Insiders only. There, no separate install is needed. If you're on stable, you do need to install it manually; there's some features of js-debug--such as the package.json code lens and "Attach to Node.js Process (preview)" command that surface whenever it's installed--that people would notice we didn't want to open the floodgates quite yet.

The "old" Debugger for Chrome extension is needed _if_ you use `type: "chrome"` and `debug.chrome.useV3` instead of using `type: "pwa-chrome"` in your launch configs directly directly. This is needed because of the way useV3 works: the "old" chrome debugger's configuration step looks for that flag and, if present, redirects the debug request to js-debug; js-debug itself does not listening for the "chrome" type.

**Comment by jtsom** [comment]
Thanks. I do use Insiders so I guess I don't need to keep it installed (guessing it doesn't hurt if it's there?) One less extra extension taking up space.

**Comment by connor4312** [comment]
If you use pwa-chrome as your debug type, then you don't need the chrome debugger installed, only js-debug 🙂
