### ISSUE TITLE
Use package.json location to determine the default program root

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#326]
I get bugs when using request: "pwa-node" but everything works ok when i use "debug.node.useV3": true in the settings.
Whats the difference, i thought both are using the new debugger?

Thanks

**Comment by connor4312** [comment]
That's interesting--usually we've seen the opposite 🙂  

The process for launching a debug session is roughly:

 1. Hit "start session"
 2. VS Code asks the debug extension registered for the `type` to fill in the config--resolving defaults and such
 3. VS Code takes the resolved config and starts a session

The existing debuggers are still registered for types like `node` and `chrome`. The `useV3`tells tells them at that step to, instead of returning a confirm with the same debug type, return a config with the `pwa-` prefix to point to the new debugger. Step 2 doesn't happen again, so this means that defaults get filled in by the old debuggers instead of the logic in js-debug.

This has been the sources of a handful of bugs where we were expecting some new behavior that the old debugger didn't implement, or a new option that we didn't get a default for in step 3. But this is the first issue I've heard of pwa- failing and the non-prefixed one working! Can you describe the bugs are you running into?

**Comment by jasonwilliams** [comment]
`ts-jest` issue, Im running a test and setting a breakpoint.
When i use `pwa-node` it completely crashes (like, i have to restart VSCode). 
But using the useV3 works ok.

Im on VSCode Version: 1.42.0 Stable

```
    {
      "name": "(CMS UI) Launch Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceFolder}/ui-cms",
      "runtimeArgs": ["./node_modules/.bin/jest"]
    }
```

**Output**
```
Note: Using the "preview" debug extension
Verbose logs are written to:
/Users/[User]/Library/Application Support/Code/logs/20200211T172326/exthost1/ms-vscode.js-debug-nightly/vscode-debugadapter-0.json
/usr/local/bin/node ./node_modules/.bin/jest
Debugger listening on ws://127.0.0.1:65439/50bb7dcc-feb5-4a18-a800-fddfaf3dec4e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
```

It gets to "Debugger attached." then crashes, it does nothing after this.
https://gist.github.com/jasonwilliams/29623ce7b2893a71c1c7e2e1c6f46e47

After creating a trace im now wondering if the crash is because of how many files it seems to be going through.

**Comment by jasonwilliams** [comment]
Both versions "Creating source from url" for every single node module, is there a way to skip anything inside of "node_modules" ?

**Comment by connor4312** [comment]
Thanks for the logs, I see some of why it's stopping in the code you've shared: it's a "pause" for us to parse a sourcemap, at which point the debugger just stops and doesn't continue. Are you able to share a link to the project you're working on so I can narrow down why it's not resuming?

> Both versions "Creating source from url" for every single node module, is there a way to skip anything inside of "node_modules" ?

Unfortunately not. Those sources are shown in the "Loaded Scripts" view on the side, and is information to create a stacktrace when paused, for example.

**Comment by jasonwilliams** [comment]
Unfortunately the problem doesn't happen when i break it out into a test case

**Comment by connor4312** [comment]
Hmm, the search paths for source maps is determined by the `outFiles`, which defaults to all JS files in your project excluding node_modules:

```
"outFiles": [
  "/Users/[User]/workspace/project/**/*.js",
  "!**/node_modules/**"
],
```

In the logs you sent it seems like this is working; I'm not seeing it parsing from a different folder and both the `pwa-node` and `node` logs contain about the same amount of `sourcemap.parsing` events.

`no sourceRoot specified, using script dirname` is expected for TS files running in Node, that's mostly diagnostic.

**Comment by jasonwilliams** [comment]
> Hmm, the search paths for source maps is determined by the outFiles, which defaults to all JS files in your project excluding node_modules:

Thats interesting, I wasn't aware of this.
I work in a monorepo and i have the whole repo set as my workspace, (I'm sure others work in this way to). So i should probably scope that down to the folder i care about for this launch task.

Is a good default? I feel it's not obvious behaviour.

Could there be some sort of root property it uses instead? or using tsconfig.json as the root?.
I wouldn't know to set outFiles unless i have my sourcemaps in a very specific place, i wonder if there should be some documentation surrounding "outFiles" to explain this.

I will try changing "outFiles" to the folder i care about and see if that changes anything and come back to you.

**Comment by jasonwilliams** [comment]
Using "outFiles" fixes it, thanks

**Comment by connor4312** [comment]
I'm not sure either. In fact there's a log line in the pwa-node version saying that prediction successfully completed after 5.5 seconds. Maybe the log shared originally was the wrong one?

```
{"tag":"perf.function","timestamp":1581444436585,"message":"","metadata":{"method":"BreakpointsPredictor.createInitialMapping","duration":5516},"level":0}
```

I believe that outFiles defaulting to the entire workspace is a good default to most users. Alternatively, maybe it should default to the closest `package.json` relative to the debugged program? I believe Lerna et al. generally have package.json's in each submodule, so that could be a decent heuristic.

cc @roblourens

**Comment by jasonwilliams** [comment]
> I believe that outFiles defaulting to the entire workspace is a good default to most users. Alternatively, maybe it should default to the closest package.json relative to the debugged program? I believe Lerna et al. generally have package.json's in each submodule, so that could be a decent heuristic.

Yeah, i think that should be a fine heuristic to go by.
Even if you decide not to do this, It's worth documenting the behaviour of "outFiles" anyway because i wouldn't have suspected it to work like that.
