### ISSUE TITLE
Edge reuses existing windows inappropriately

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode-js-debug#340]
When using `"runtimeExecutable": "dev"` in my launch config (below), it opens a new tab in an existing Window and then errors out on attaching:

![image](https://user-images.githubusercontent.com/641685/74961151-9b7fab00-53db-11ea-9e75-cf47e06c0987.png)

Where as if I try it without the `dev` flag, it works properly.

Launch config:
```json
{
	"type": "pwa-msedge",
	"request": "launch",
	"name": "Launch",
        "runtimeExecutable": "dev",
	"url": "http://localhost:8080",
	"webRoot": "${workspaceFolder}",
	"sourceMaps": true,
	"trace": true
}
```

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/commit/cc00e41b2116026dc4384753357fcc18a308adbb#diff-8c4043e331960a073f1179c582377f3c. We weren't handling the user data dir like the config option promised, and we were using a hardcoded list of Chrome's versions to determine whether to add a user data dir (instead of the new `isQuality` that added support for Edge's qualities).
