### ISSUE TITLE
Detect default browser and use that for debugging

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-js-debug#417]
I use Edge locally and would prefer to use that for debugging as well (without needing to configure anything).

**Comment by connor4312** [comment]
To verify:

 1. Set your default browser to Edge
 2. In the debug terminal, type any address (e.g. `https://github.com`)
 3. Ctrl+Click on it. Verify that it opens and is debugged in Edge rather than Chrome.

Note that the default browser is cached, so if you change your browser after clicking a link you'll need to reload to have the change apply.

**Comment by aeschli** [comment]
Verified on Linux with Firefox
