### ISSUE TITLE
NPE: Welcome view button throws

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode-js-debug#451]
When clicking the `Node.JS Debug Terminal`:

![image](https://user-images.githubusercontent.com/22350/80492743-be42b880-8964-11ea-8257-00b361b5e964.png)

**Comment by joaomoreno** [comment]
GitHub is acting up, I can't remove myself from assignees. @connor4312 this is for you.

**Comment by connor4312** [comment]
This is fixed in the latest Insiders -- there was an API that was renamed (https://github.com/microsoft/vscode/commit/8ec6ec7dc128b949f445ba254eabc8e931e90f78) which I published for; if users on insiders manually updated from the built-in version during those couple hours they would have been broken.
