### ISSUE TITLE
"stack frame not found"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#455]
- Debug normally
- Hit a breakpoint
- Click the second stack frame item
- Can't see variables past the first frame

I don't see anything obvious in the log?

![image](https://user-images.githubusercontent.com/323878/80865473-5edbf580-8c4f-11ea-9bce-90c583543e5b.png)

[vscode-debugadapter-7.json.txt](https://github.com/microsoft/vscode-js-debug/files/4567790/vscode-debugadapter-7.json.txt)

**Comment by connor4312** [comment]
@isidorn I'm seeing something interesting here, the case is:

 1. Rob pauses on a breakpoint here: https://github.com/microsoft/vscode/blob/d9b9744ce7ef30abc63ab456de10bc5035b3d291/src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts#L104
 2. VS Code requests a stacktrace. For the"fire" frame he has in the screenshot above, js-debug responds with stacktrace id A (in the log, `692`)
 3. Rob steps over a statement.
 4. We continue and stop again, as expected. VS Code requests a new stacktrace. 
 5. VS Code requests a new stacktrace for this location. This time, the "fire" frame has a frame id B (in the log, `722`)--for us stacktraces are ephemeral and we just auto-increment for each new set of data from CDP.
 6. Rob clicks on the "fire" frame, but it sends a request with id A that we no longer have 🐛

**Comment by isidorn** [comment]
@roblourens thanks for filling great issues
@connor4312 thanks for making good repro steps

The issues was the following: we are doing delayed call stack loading which means we first fetch the top then the rest. If the rest is same as in previous step we do not fire a change event to reduce tree flashing. The issue was in our equality check for frames. We were not checking that the frameId were equal which was very much wrong.
