### ISSUE TITLE
Error loading bootloader.bundle.js when forking a new node process with a gid or uid  

### ISSUE THREAD

**Issue by omardelrio** [microsoft/vscode-js-debug#465]
When forking a node process with the following options (partial code): 
``` javascript
const opts = {
        stdio: "inherit",
        execArgv: [someArg],
         uid: anotherUser.uid,
         gid: anotherUser.gid
    };
const proc = child_process.fork(child_process_module, args, opts);
```

The debugger, when attaching to the process, throws the following error: 

```
Error: Cannot find module '/root/.vscode-server/extensions/ms-vscode.js-debug-nightly-2020.5.1117/src/bootloader.bundle.js'
Require stack:
- internal/preload
    at Function._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at internal/modules/cjs/loader.js:1125:12
    at loadPreloadModules (internal/bootstrap/pre_execution.js:443:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
    at internal/main/run_main_module.js:7:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'internal/preload' ]
```

If I remove the uid/gid, the debugger attaches correctly. Note that the debugger attaches to the parent process with no problems, and the file does exist. 

The app is running inside a container, and the parent process creates the users and groups as needed. The parent process is running as root inside the container.

**Comment by connor4312** [comment]
1. Does `chmod 755 /root/.vscode-server/extensions/ms-vscode.js-debug-nightly-2020.5.1117/src/bootloader.bundle.js` make it work? I could have js-debug ensure the file is globally readable by default...

2. Otherwise, you can overwrite the import of the bootloader by setting

     ```
     env: {
       NODE_OPTIONS: ''
     }
     ```

     This means you won't get automatic debugging on the child process, but it won't crash.

**Comment by omardelrio** [comment]
Thank you for the pointer - 

Default permissions for /root: 
drwx------   4 root     root     

Turns our we need o+x so that other users besides root can read the file.
So chmod 755 on the file is not enough, it actually needs o+x in the /root folder.

This is under Alpine. 

Doing that the error goes away (and the debugger attaches, but my process ends with SIGTERM, which could be an issue with my code) - but now I am wondering if I should just run the child processes under root (or the root group) while debugging to avoid this.

**Comment by connor4312** [comment]
Okay, thanks. I figured that just changing bits on the file alone wouldn't be enough--and it is of course not safe to have the debugger recursively change permissions like that--but it was worth a shot. 

It sounds like you have a two workarounds available:

 - Clearing the NODE_OPTIONS as I mentioned above. If you'd like to debug the children, you can still add the `--inspect` flag in the `execArgv` and attach manually once they spawn.
 - Running them under the root, if that works for you; you could set an environment variable in your launch config (the option is called `env`) and launch them as root when that's present.

Because this is an edge case and a problem inherent to the structure of how js-debug works, it doesn't sound like there's a change to make in this repo. Give me a shout if you run into any more issues 🙂
