### ISSUE TITLE
Evaluate fails due to: Cannot read property 'objectId' of undefined

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#485]
We are getting a lot of telemetry where the evaluate requests fails due to: Cannot read property 'objectId' of undefined

This happens on this line https://github.com/microsoft/vscode-js-debug/blob/master/src/adapter/variables.ts#L45 because object is null. 

Stack trace:
```
TypeError: Cannot read property 'objectId' of undefined
    at new p (variables.js:33:32)
    at _.createVariable (variables.js:188:41)
    at k.result [as evaluate] (threads.js:296:46)
    at a._onMessage (connection.js:140:27)"

```

**Comment by connor4312** [comment]
Are you able to capture a `trace: true` log with a reproduction for this?

**Comment by digeff** [comment]
This is from telemetry, I don't know how to reproduce this :(

**Comment by connor4312** [comment]
This happens if the result is undefined: https://github.com/microsoft/vscode-js-debug/blob/05f53731f2ae7f3d30bb581648fc04c03622f2d9/src/adapter/threads.ts#L423

(This code path is hit for non-REPL evaluation requests, like watch expressions or clipboard requests)

According to the CDP documentation, this should never happen. Wonder if it's something in Blazor or RN. Unfortunately I've not yet been able to debug with blazor to try that out.

**Comment by digeff** [comment]
This seems to happen on Blazor only, so re-filed the bug there: https://github.com/dotnet/aspnetcore/issues/22375
