### ISSUE TITLE
Unbound breakpoints since enabling preview (after VS Code upgrade) due to `EMFILE`

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/vscode-js-debug#595]
**Describe the bug**
Before upgrading VS Code, my Node attach debug config worked fine, but since upgrading VS Code (which enabled the new debugger) my breakpoints no longer work. When I hover over them it says "unbound breakpoint".

After setting a breakpoint and then starting the debugger, I see an error along the lines of:

```
Error processing setBreakpoints: Error: EMFILE: too many open files, scandir '/Users/oliverash/…
```

Sometimes I see a notification with this error, but it doesn't always seem to appear.

**To Reproduce**
Unfortunately I was not able to create a reduced test case.

**Log File**

[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/4914713/vscode-debugadapter-1.json.gz)

**VS Code Version:** 1.47.0

**Additional context**

If I set an explicit `outFiles` then it seems to work. However I didn't need this before?

```json
"outFiles": ["${workspaceRoot}/dist/server/**/*.js"]
```

I am using Node version 12.8.1.

**Comment by connor4312** [comment]
Thanks for the issue! By default js-debug will scan the entire workspace for sourcemaps. We don't throttle the number of open files, which we should have don. But this is now fixed since as of https://github.com/microsoft/vscode-js-debug/commit/b472d69b53b0d0269614e97495b303f450397526 we'll use VS Code's file searching (backed by ripgrep) rather than searching ourselves. You can use the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension) if you'd like to try this out.

Let us know if you hit any other problems.

**Comment by OliverJAsh** [comment]
I'm still running into this with VS Code 1.47.2.

**Comment by connor4312** [comment]
The change reference will only be on nightly until the July release of VS Code, which will be 1.48.
