### ISSUE TITLE
Way slower than old js debugger module

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode-js-debug#598]
**Describe the bug**
We are experiencing slow launch/initialisation/reload times with both our Chrome extension since upgrading to VSCode 1.47.0

This new module must be the culprit, as this slowdown has occurred across 3 different machines, two are Mac and one is Ubuntu. Caused up to 30 seconds of time between hot reloads on two computers, and caused a more powerful computer's fans to spin up hard for long periods of time.

I want a way to use the old debugger, I don't need new features if it's going to cause such a big performance hit.

Downgrading to VSCode 1.46 brings back normal performant behavior.

1 months in Insiders is way too little time to iron out the kinks, this was pushed out too early. Should have at least had a way for people to opt out.

Why did you guys swap them out anyway? If it ain't broke...

**Comment by connor4312** [comment]
You can use the option `debug.javascript.usePreview: false` to use the old debugger, but this will eventually go away as js-debug stabilizes.

Please provide a trace log using these instructions and I can take a look at why it's being slow for you:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by jpike88** [comment]
I'll instruct our devs to do this and attach the logs to this issue ASAP

**Comment by AlbertoMontalesi** [comment]
Here's the log i've got

[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-js-debug/files/4916566/vscode-chrome-debug.txt)

**Comment by connor4312** [comment]
@AlbertoMontalesi thanks for the log, but that's from the old debugger. Can you take a log without setting `debug.javascript.usePreview: false`?

**Comment by AlbertoMontalesi** [comment]
@connor4312 
My bad

[debug.json.zip](https://github.com/microsoft/vscode-js-debug/files/4916662/debug.json.zip)

**Comment by connor4312** [comment]
Great, thanks. I see what's happening -- we actually have an optimized mode for these kinds of scenarios, but it looks like your sourcemaps start with `ng:///` rather than `webpack:///` so our logic wasn't kicking in. I don't get this case in a new Angular project from the CLI so I can't test it locally, please confirm whether it works for you.

You can wait until 5 PM PST today to grab the latest [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension), or manually installed (`Install from VSIX` command) this pack I manually built: https://memes.peet.io/img/js-debug-nightly-issue-598.vsix

**Comment by AlbertoMontalesi** [comment]
@connor4312 From an initial test it seesm that the nightly build works fine and performance is back to normal. I noticed that everytime a hot reload occurs the debug panel opens by itself, it didn't occur with the old debugger, it's a bit annoying because i have to keep closing it manually. Not sure if it's related to this extension or not.

![image](https://user-images.githubusercontent.com/23130353/87501612-b5bb6d80-c689-11ea-9a9f-2ec10e2e76d3.png)

**Comment by connor4312** [comment]
Perhaps we open it whenever session change. You can control this via the `debug.openDebug` setting as well.

**Comment by connor4312** [comment]
It looks like the setting `debug.openDebug` defaults to `openOnSessionStart` -- and when you reload the page, the previous page's session is destroyed and a new one is created, so this is technically doing the right thing. `debugOnFirstSessionStart` seems like what you want and might be a more reasonable default. I'll open an issue to see if we should change that.

**Comment by AlbertoMontalesi** [comment]
@connor4312 awesome thanks, i've set it now to `openOnFirstSessionStart`
