### ISSUE TITLE
[Feature request] Show progress indicator while loading source-maps

### ISSUE THREAD

**Issue by digeff** [microsoft/vscode-js-debug#606]
**Is your feature request related to a problem? Please describe.**
Users get confused as to why the debugger sometimes takes a long time to load a page, and as to why breakpoints are not always hitting

**Describe the feature you'd like**
Let's use the dap:ProgressStart to notify the client of long operations like parsing source-maps, so we can wait/block more time for time without users getting annoyed, and also giving them the option to cancel them if they don't want to wait.

**Comment by connor4312** [comment]
Not sure I want to do this. Usually sourcemap parsing will be fairly instant and not worth notifying the user about, and there is no defined or known end time for this parsing.

**Comment by digeff** [comment]
Do we have telemetry or any data to measure how much time we spend parsing source-maps?

**Comment by connor4312** [comment]
Thanks to your PRs, we're now smarter about this and capture more telemetry. Also, since July we've improved discovery so the big block of _initial_ sourcemap parsing should be much faster now (but still, since we're walking a file tree, we don't know up front whether it'll take 2ms or 2000ms). In cases where parsing is not fast, we emit an alert and suggest to the user that they narrow their `outFiles`. At the present time I don't have plans to do anything further here.
