### ISSUE TITLE
Unable to inspect variables in JS debug

### ISSUE THREAD

**Issue by danieldonaldson** [microsoft/vscode-js-debug#641]
Unable to inspect variables in JS debug. When printing an array to the console, it shows the arrow to the left, which expands the array. This is no longer working - now when clicking the arrow it just shows the spinning circle 'thinking' icon

1. Add console.log to array variable
2. Click on debug (F5)
3. Attempt to inspect variable while program is running

**Log File**

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/4948420/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.47.2

**Additional context**
Was working fine a week ago

**Comment by connor4312** [comment]
Thanks for the issue. I see that you ended the debug session about 3 seconds after expanding the array -- this is after we ask Chrome to run the following function on the array to enumerate its properties:

```
function getArrayProperties() {
    const result = { __proto__: this.__proto__ };
    const names = Object.getOwnPropertyNames(this);
    for (let i = 0; i < names.length; ++i) {
        const name = names[i];
        const numeric = name >>> 0;
        // Array index check according to the ES5-15.4.
        if (String(numeric >>> 0) === name && numeric >>> 0 !== 0xffffffff) {
            continue;
        }
        const descriptor = Object.getOwnPropertyDescriptor(this, name);
        if (descriptor) {
            Object.defineProperty(result, name, descriptor);
        }
    }
    return result;
}

getArrayProperties.call(myArray);
```

I wonder if you get the same slow/infinite delay if you run that on the array manually?

**Comment by danieldonaldson** [comment]
Thanks for the quick response! I ran this code on the same array and it works fine. But then when trying to log it to console, it seems to stop the entire program executing.

Trace for running in debug: 
[vscode-debugadapter-5.json.gz](https://github.com/microsoft/vscode-js-debug/files/4948704/vscode-debugadapter-5.json.gz)

Seems to do the same when trying run without debugging:
[vscode-debugadapter-6.json.gz](https://github.com/microsoft/vscode-js-debug/files/4948702/vscode-debugadapter-6.json.gz)

But, runs fine from terminal

**Comment by connor4312** [comment]
That's interesting, and explains why it looks like that function stalls.

In that last log, js-debug doesn't even send anything over to Node/V8 -- if I'm understanding right it seems like logging that (with a debugger attached) deadlocks the Node process. As a result of this I would suggest doing three things:

1. If it's not hard for you to switch, seeing if you can reproduce it on the latest Node 14.5.0
1. See if you can get a reproduction case in a single file/snippet. If not, play around a little bit and see if you can narrow down what's the deal with the array that's causing the crash.
1. _If_ you can get a reproduction case, then try it in the Chrome devtools as well. If it happens there, the [create a bug on Chromium](https://bugs.chromium.org/p/chromium/issues/entry). Otherwise, create a [bug on Node.js](https://github.com/nodejs/node/issues/new/choose)

**Comment by danieldonaldson** [comment]
Thanks for the comments Connor and sorry for taking so long to get back to you. It happened with new Node (v14), but only within this project, and only within VSCode, and only within debug. Terminal within VSCode didn't cause anything to lock up. And the crazy thing is that it seems to be gone now, after going back to Node v12.

Guess I'll re-open if it ever comes back. Thanks for the assistance
