### ISSUE TITLE
Node.js server app basically stops?

### ISSUE THREAD

**Issue by hootyjeremy** [microsoft/vscode-js-debug#649]
**Describe the bug**
I'm trying to debug my nodejs code while writing this app but since using the new js-debug in 1.47 (default version and nightly version), the app/server will just stop at seemingly random parts of the request handling code I have. It won't freeze vscode but it's as if the server just stops running. If I run "node app.js" instead of the debugger, it doesn't ever freeze on these particular parts.

**To Reproduce**
I can see in the call stack that npm-cli.js is "running" and so is my app underneath it so I can still stop the debugger but the app will not take any more requests and is just dead, basically. It is reproduceable every time but what is odd is that as I send a request to analyze different items, it will execute and respond properly a couple of times and then it will stop during another one. Then if I restart and try the one that froze, it will work successfully and then some other one will hang. 

I did a trace of a good search and a bad search and no errors really pop up.

I don't really know how else to debug a debugger but maybe it's my launch.json? Does any of this look wrong? I try to use this with the nightly js debugger but it says there "matches multiple schemas when only one must validate" but if I use the regular debugger, it doesn't say that. What should I be doing?

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceFolder}\\pubg.js",
            "runtimeExecutable": "npm",
            "runtimeArgs": ["run-script", "debug"],
            "attachSimplePort": 9229,
        }
    ]
}
```

**VS Code Version:** Replace me!

**Additional context**

**Comment by connor4312** [comment]
Thanks for the issue, make sure you do steps 1 and 2 here, that should fixed te "matches multiple schema" issue https://github.com/microsoft/vscode-js-debug#nightly-extension

If you continue to run into this: 

1. A trace log would help (instructions in the issue template)
1. Try to make sure you're on a recent Node.js version... this smells like a Node/V8 issue rather than js-debug

**Comment by hootyjeremy** [comment]
It looks like the node.js update worked so it isn't stalling anymore. So glad about that. Thanks a lot.

I'm so close to being where I want. I like to use the Chrome DevTools for nodejs in addition to the vscode debugger and before the update, I was running the debug on port 9229 for DevTools to attach to but now the `port `configuration doesn't hold. I have read that we need to use `attachSimplePort` and set `type` to 'pwa-node' but if I do that, from the launch.json pasted previously, I get this error:

![launch error](https://user-images.githubusercontent.com/68588318/88124767-7ca46100-cb93-11ea-80c7-7a7f02dc8196.png)

Does the launch.json from the original look okay? If I use it, it will actually launch without an error but it just won't use the right port, of course.

Thanks.

**Comment by hootyjeremy** [comment]
I might have done something here... I changed my package.json to use the `--inspect` again but just not the `-brk=9229` part and it launches without an error when using pwa-node. It doesn't seem to be broken anymore and I can remote debug with DevTools as well as use the vscode debugger from what I can tell.

Maybe node stuff still needs `--inspect`? I don't know but at least I can get back to work. Thanks for doing all your work and looking at people issues on top of it.

**Comment by connor4312** [comment]
Okay, glad you got it working! I'll make a note of that Node version in case other people run into it. A cursory search of node/chrome bugs didn't find an existing issue, but it's hard to get a narrow search term for what you ran into...

For the port: Js-debug can now (automatically) debug child process, so setting a single port in the launch configuration doesn't make as much sense, since child processes won't be able to use that port. However if a process is launched with some --inspect flag, we'll respect that.
