### ISSUE TITLE
Support debugging on a Node.js WebSocket source

### ISSUE THREAD

**Issue by hjkcai** [microsoft/vscode-js-debug#668]
Hello, I'd like to ask for a feature. That is to support remote debugging on a Node.js target, which has only a WebSocket link. Currently I have to use chrome devtool to do this, by using this link: 

```
chrome-devtools://devtools/bundled/inspector.html?v8only=true&ws=
```

But if I fill my WebSocket debug link in the `address` field in `launch.json`, it does not work at all.

Thanks!

**Comment by connor4312** [comment]
Merged, thank you!

**Comment by aeschli** [comment]
Can you add verification steps?

**Comment by connor4312** [comment]
1. From any terminal, run `node --inspect`
1. Look at the "Debugger listening on <address>" and paste that into a launch config like:

```
{
  "type": "pwa-node",
  "request": "attach",
  "name": "attach",
  "websocketAddress": "ws://127.0.0.1:9229/1b964176-3c14-401c-b745-d8a168102090"
},
```

1. Verify you can launch and debug that config

**Comment by avatar414** [comment]
The ws:// url changes with each launch. Wtf?

**Comment by slavistan** [comment]
Is there a more streamlined way to do this? Changing a configuration file in order to connect to a transient debugging session is too cumbersome. In my case, I need to use the websocket uri because there are too many node processes running in the background in order for the "attach to node process" feature to be useful.
