### ISSUE TITLE
customRequest: evaluate truncation

### ISSUE THREAD

**Issue by firien** [microsoft/vscode-js-debug#689]
I am not sure if this repo is a debug adapter, or just a GUI on top of an existing adapter - so apologies if I am up the wrong tree, but I am dusting off an old debug project that is about a year old. I used `session.customRequest('evaluate', { expression: 'someFunction()' });` to get a large JSON string (~5k characters)

I think vscode [1.47.X](https://code.visualstudio.com/updates/v1_47#_debugging) uses this new debugger by default (does the README.md need an update?) and the result is now truncated to 100 characters, with the center portion replaced with an ellipsis.

As stated above, I haven't run this code in a year, so I don't know if it ran correctly on 1.46 - which i believe used the old debugger.

**Comment by connor4312** [comment]
We bumped this to 100k characters in the [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Since you method a DAP message it sounds like you're developing an extension and talking to DAP directly; you can avoid truncation by adding `context: 'clipboard'` to the arguments, which will never truncate the value.

**Comment by firien** [comment]
thank you. just downgraded to 1.46 before your message to check my sanity.
