### ISSUE TITLE
Unable to attach to browser on macos

### ISSUE THREAD

**Issue by jeiea** [microsoft/vscode-js-debug#697]
- VS Code Version: 1.47.0
- Log file (set `"trace": true` in launch config): [vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-chrome-debug/files/4901127/vscode-debugadapter-0.json.gz) (I know it's broken, but I tried twice.)
- vscode-chrome-debug version: 4.12.9

# What I did
1. Save `launch.json` with the following
```jsonc
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8080",
      "webRoot": "${workspaceFolder}",
      "userDataDir": "${workspaceFolder}/.vscode/chrome",
      "trace": true
    }
  ]
}
```

2. Press F5

# What I expected
Normal launch

# What I got
![image](https://user-images.githubusercontent.com/4188984/87119467-05302100-c2b9-11ea-8bc0-d1ecedbf4169.png)

# Additional context
4.12.8 doesn't have this problem. It may be a regression.

**Comment by connor4312** [comment]
I'm calling this 'fixed' with https://github.com/microsoft/vscode/issues/103083#issuecomment-671620059, since that's by far the most common case where this issue happens -- aside from just an attach config where the url or filter doesn't match. If you continue to run into this problem:

1. Use the nightly build https://github.com/microsoft/vscode-js-debug#nightly-extension
1. If your issue continues to happen there, file an issue using this template: https://github.com/microsoft/vscode-js-debug/issues/new/choose

**Comment by jeiea** [comment]
Then it is a confirmed regression? It's so sad I can't do the thing worked well with the previous version...

**Comment by connor4312** [comment]
It is allow if and only if you choose to launch chrome with a `port`. For security reasons, by default the new debugging launches Chrome with a remote debugging pipe via its stdio. This means that when js-debug launches the browser, it must be in control of the browser arguments, but if a browser is already opened in the user data dir Chrome will ignore the arguments and 'merge' with the previous launch.

**Comment by csutorasr** [comment]
I have an open chrome on the Mac Os  docker. I clicked on it and pressed cmd+Q.

Afterwards it could reopen it.
