### ISSUE TITLE
Angular breakpoints/sourcemaps stop working after changes to files.

### ISSUE THREAD

**Issue by captainkout** [microsoft/vscode-js-debug#730]
**Describe the bug**
Angular breakpoints/sourcemaps stop working after changes to files.

**To Reproduce**

This is the same problem noted here https://github.com/microsoft/vscode/issues/103844 and here https://github.com/microsoft/vscode/issues/101762.

There are log files available and steps to reproduce the problem on the existing issues. The issues were merged with another Webpack issue regarding sourcemaps. Since then the problem has been identified as a unique issue to Angular.

**VS Code Version:** 
1.48 with Nightly Debugger

**Comment by captainkout** [comment]
This is the same problem noted here https://github.com/microsoft/vscode/issues/103844 and here https://github.com/microsoft/vscode/issues/101762

**Comment by connor4312** [comment]
Ah, sorry for the confusion. I didn't remember that you were the one who opened that initial issue. Regardless I'll leave this and the linked issue open for investigation.

**Comment by connor4312** [comment]
While the commit I linked earlier fixed a different case, it added infrastructure that made fixing the ng case easy. It seems to work well for me now.

Please try this out in the next nightly build and let me know how it goes!

**Comment by captainkout** [comment]
@connor4312 Do we need to be on the VSCode insiders edition to verify this update? I am on 1.49.0 insiders with JS Debugger (nightly) v2020.8.3118 and have experienced success this morning. But others on my team are still reporting errors.

**Comment by connor4312** [comment]
Yes, the latest nightly only works on Insiders since there are new API dependencies this month. The next stable release should happen in just over a week.

**Comment by jarrodldavis** [comment]
I'm running into a similar issue with Next.js. I have API routes that work fine initially, but then don't work after making changes (that Next.js recompiles).

I'm using this for the launch config:
```json
    {
      "name": "Attach to Server",
      "type": "pwa-node",
      "request": "attach",
      "skipFiles": ["<node_internals>/**"]
    }
```

which attaches just fine with a `yarn dev` script like so (`package.json`):

```json
{
  "scripts": {
    "dev": "NODE_OPTIONS='--inspect' next dev",
  }
}
```

Visual Studio Code info: 
```
Version: 1.49.0-insider
Commit: e4256dd1a02339bb1d56647ecd9134bf38bc7c03
Date: 2020-09-04T18:47:13.407Z (3 days ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

Debugger info:

`ms-vscode.js-debug-nightly` version `v2020.9.417`

**Comment by connor4312** [comment]
Next.js does things differently and we do not support it at the moment.

**Comment by jarrodldavis** [comment]
What are the differences (as far as I’m aware, Next.js uses webpack and hot reloading) and is there any ETA on supporting Next.js? It’s really frustrating to have breakpoints stop working correctly for even the smallest of changes.

**Comment by connor4312** [comment]
I made some fixes here https://github.com/microsoft/vscode-js-debug/commit/1759060a27a1c1ea4cdb96543ce526e8c7050acd

Next.js still does some weird things. Well, things that make life difficult for us. Namely, when they recompile, the new source is not actually loaded until you try to load the page, so during this time the file on your disk and the script in the runtime are different. During this period, breakpoints are likely to appear at incorrect locations, since we'll still be loading the old sourcemap.

Also, because of this, we do not know that the page's source updated until it's about to run, so on the first refresh after a change it's likely breakpoints will get missed. Chrome has an option we can use to ask it to pause before executing a script with a sourcemap, but Node.js has no such option.

However after this point breakpoints should work. I'll open an issue on them to see if they can change this behavior, at least while running with an inspector attach.
