### ISSUE TITLE
Crashes Chrome

### ISSUE THREAD

**Issue by kennetherland** [microsoft/vscode-js-debug#738]
I wasted a whole day, thousands of dollars to me, trying to figure this out.  I wish I could charge Microsoft for the time I wasted.  Once I saw the following: revert to the old behavior, you can set "debug.javascript.usePreview": false, I knew.  Please test your code before pushing it out please.   Your new rapid-fire release cycle exploits your customers as your pee-on beta testers.  It does not work.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/729. The Chrome team has indicated this will be fixed in the next version, and it should work on Chrome Canary (instructions: https://github.com/microsoft/vscode-js-debug/issues/729#issuecomment-683367574). Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1123329
