### ISSUE TITLE
nyc.wrap() making breakpoint unbound

### ISSUE THREAD

**Issue by ShenChen-Amazon** [microsoft/vscode-js-debug#745]
**Describe the bug**
I was following the [testRunner](https://github.com/microsoft/vscode-js-debug/blob/master/src/test/testRunner.ts) and use the nyc to generate test coverage report. Here is my repo: https://github.com/ShenChen-Amazon/ask-toolkit-for-vscode/blob/master/test/index.ts.

However, with nyc enabled, I can no longer hit the breakpoint set in my src code. I am still able to hit the breakpoints in test files. [Here](https://github.com/ShenChen-Amazon/ask-toolkit-for-vscode/blob/master/.vscode/launch.json#L20) is the test config I use.

I've seen there's a popular topic related to debug.javascript.usePreview setting, but it doesn't work even if i disabled it. But if I disable the nyc.wrap() function, I can successfully hit the breakpoint but the generated coverage report will be empty...

**To Reproduce**
1. Fork my repo: https://github.com/ShenChen-Amazon/ask-toolkit-for-vscode/blob/master
2. Download dependencies
3. Set up some breakpoint under src/extension.ts, inside the activate() function
4. Go to debug tab, choose extension tests, and run the task
4. None of the breakpoints will be hit

**VS Code Version:** 1.48.2

**Comment by connor4312** [comment]
This is expected, since nyc doesn't generate sourcemaps for its code and moves lines/columns around. I recommend not using nyc during debugging; even if you convinced it to create sourcemaps (which might be possible, I'm not an nyc expert) debugging would not work as expected, since you would hit lots of the 'invisible' statements it inserts to create its coverage map.
