### ISSUE TITLE
Remote debug port

### ISSUE THREAD

**Issue by s4m0r4m4** [microsoft/vscode-js-debug#753]
**Describe the bug**
When switching from the old debugger to this one (by toggling "`debug.javascript.usePreview`" to true), the debugger is no longer able to attach to an electron process running with `remote-debugging-port`.

**To Reproduce**
1. Web/angular launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Red Hand: Renderer",
            "type": "chrome",
            "request": "attach",
            "port": 9224, // must match red-hand-main launch.json
            "webRoot": "${workspaceFolder}",
            "timeout": 25000,
            "sourceMaps": true,
            "urlFilter": "http://localhost:4202/*"
            "preLaunchTask": "RedHand: NgServe
        }
    ]
}
```
2. Electron launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Red Hand: Main Static",
            "type": "node",
            "request": "launch",
            "port": 5858,
            "protocol": "inspector",
            "cwd": "${workspaceFolder:red-hand-main}",
            "sourceMapPathOverrides": {
                "webpack:///./~/*": "${workspaceFolder:red-hand-main}/../../node_modules/*",
                "webpack:///./*": "${workspaceFolder:red-hand-main}/../../*",
                "webpack:///*": "${workspaceFolder:red-hand-main}/../../*"
            },
            "runtimeExecutable": "${workspaceFolder:red-hand-main}/../../node_modules/.bin/electron",
            "windows": {
                "runtimeExecutable": "${workspaceFolder:red-hand-main}/../../node_modules/.bin/electron.cmd"
            },
            "args": [
                "--inspect=5858", // must match "port" above
                "--remote-debugging-port=9224", // must match port in red-hand-ui launch.json
                "${workspaceFolder:red-hand-main}/../../dist/apps/red-hand-main/main.js", // path to entry file (if relative,relative to cwd above)
            ],
            "sourceMaps": true,
            "outputCapture": "std",
            "preLaunchTask": "RedHand: BuildMain"
        },
```
3. Set "`debug.javascript.usePreview: false`" and put a breakpoint in one of the files that is run in the browser of the electron app. This breakpoint will catch (may have to reload window, but that was a preexisting condition)
4. Set "`debug.javascript.usePreview: true`"  and restart the debug configs, and the breakpoint will not catch anymore.

**Log File**

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5211506/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.49.0

**Additional context**

**Comment by connor4312** [comment]
In the launch configs, I see that when we try to attach we get:

```
connect ECONNREFUSED 127.0.0.1:9224
```

Can you confirm that the app is properly listening on that port?

**Comment by s4m0r4m4** [comment]
Hi @connor4312, thanks for the quick response. Yes, I can confirm that the app is properly listening on port 9224. When I turn off usePreview, it is able to connect no problem (see attached log file, I also have the vscode-chrome-debug.txt file if you want it).
[vscode-debugadapter-1.json.gz](https://github.com/microsoft/vscode-js-debug/files/5218617/vscode-debugadapter-1.json.gz)

As mentioned in the issue description, I am launching the electron app with `--remote-debugging-port=9224`. Do I perhaps need to do something different to work with the new debugger?

**Comment by connor4312** [comment]
Thanks for the log. I think some of our logging is misleading, I misread the original log.

I'm seeing this which I've never seen before and is quite bizarre:

![](https://memes.peet.io/img/20-09-81e50011-2b26-41ad-87d6-3d8e0fafdd5f.png)

What version of Electron are you using? This seems like an issue for them...

Also, if you have the vscode-chrome-debug.txt, feel free to attach it. I'm curious what's happening differently in that case to allow it to work.

**Comment by s4m0r4m4** [comment]
I'm using electron v9.3.0.

Here are the logs:
- The old debugger catches breakpoints in both the main & renderer process (only after reloading the page, but that was the case before so not an issue here): 
   - Renderer log: [vscode-chrome-debug-works.txt](https://github.com/microsoft/vscode-js-debug/files/5224973/vscode-chrome-debug-works.txt)
   - Main log: [debugadapter-legacy.txt](https://github.com/microsoft/vscode-js-debug/files/5224977/debugadapter-legacy.txt)
 log: 
- The new debugger catches breakpoints in the main process, but not the renderer process, even after reloading (breakpoints show as "unbound" in vs code):
   - Renderer log: [vscode-debugadapter-10.json.gz](https://github.com/microsoft/vscode-js-debug/files/5225034/vscode-debugadapter-10.json.gz)
   - Main log: [vscode-debugadapter-11.json.gz](https://github.com/microsoft/vscode-js-debug/files/5225018/vscode-debugadapter-11.json.gz)

I also noticed something else that may prove useful:
- when I switch to use the new debugger, it doesn't actually launch electron if I pass an "--inspect-brk=5858" argument in launch.json - see [vscode-debugadapter-inspect-brk-no-work.json.gz](https://github.com/microsoft/vscode-js-debug/files/5224933/vscode-debugadapter-inspect-brk-no-work.json.gz). It shows the correct command to start up the electron process (`C:\...../node_modules/.bin/electron.cmd --inspect-brk=5858 --remote-debugging-port=9224 C:\..../main.js`), but nothing happens. If I run that command line myself it lauches just fine.
- It does work if I pass --inspect=5858 instead - see [vscode-debugadapter-inspect-works.json.gz](https://github.com/microsoft/vscode-js-debug/files/5224922/vscode-debugadapter-inspect-works.json.gz)).
- It also works if I use --inspect-brk and the old debugger: [debugadapter-legacy.txt](https://github.com/microsoft/vscode-js-debug/files/5224954/debugadapter-legacy.txt)

**Comment by connor4312** [comment]
Hm. I tried Electron 9.3.0 with my sample app and I didn't run into issues. Can you share how you're creating the browser window from the main process? Maybe something special is happening there.

Alternately if the code you're working on is open source or you're able to share a repro with me that could also be helpful.

Wrt --inspect-brk, that's a known behavior. A trickle of people have run into it, I've been meaning to write a reference point and [have now done so](https://github.com/microsoft/vscode-js-debug/blob/master/COMMON_PROBLEMS.md#my-app-doesnt-start-run-and-i-use---inspect-brk-to-load-it) if you're curious about why that is.

**Comment by s4m0r4m4** [comment]
Thanks for the note about --inspect-brk, that helped clear things up for me.

Since I'm serving up an angular application, for dev/debug purposes I load it up like this:

- BrowserWindow.loadURL(`http://localhost:${env.RendererAppPort}`);

For production I load a built index.html file, but I don't do debugging there so obviously not an issue.

Unfortunately my code is part of a large proprietary code base, so I cannot share directly. I could try to whip up a minimum reproducible example if need be, but I was kinda hoping the logs above would clear things up. Let me know!

**Comment by connor4312** [comment]
Hm, okay. Unfortunately this logs alone aren't too useful, though it did refresh my memory a bit. The old debugger didn't deal with the browser as a whole, since it only knew how to attach to a single page. However, the new debugger can attach to multiple tabs, service workers, frames, and so on. It does this by using the "Target" domain in the Chrome Debug Protocol, which the old debugger didn't touch, and that's where the "Not allowed" error is getting thrown.

> BrowserWindow.loadURL(http://localhost:${env.RendererAppPort});

I'm curious how the `BrowserWindow` is actually getting created; as far as I can see in the docs that's an instance method.

Failing that, if you are able to create a repo, that would be super helpful. There are a few electron app 'hello worlds' you could use a starter and apply logic until you hit the problem. I'm also happy to jump on a screenshare/Teams call if you have a few minutes. No guarantee I'll find anything, but that would let me see if anything jumps out around how Electron is being created/managed...

**Comment by s4m0r4m4** [comment]
Yeah sorry that was a bit confusing, loadURL is indeed an instance method and I was just trying to indicate that the object I was using was of type BrowserWindow. Here's a better code example:
```
app.on('ready', functionOnReady);

//... later in functionOnReady:

const cWebPreferences: WebPreferences = {
    nodeIntegration: true,
    backgroundThrottling: false,
    allowRunningInsecureContent: false
};

if (bIsDev) {
    // used to bypass CORS for log upload, only needed for dev
    cWebPreferences.webSecurity = false;
}

const cMainWindow = new BrowserWindow(
    {
        width: nWidth,
        height: nHeight,
        x: nOffsetX,
        y: nOffsetY,
        show: false,
        webPreferences: cWebPreferences
    });
```

I will try to a get a minimal repro going as well, sounds like that will be needed.

**Comment by s4m0r4m4** [comment]
I copy-pasted my repo to another folder, ran npm install, and now the breakpoints catch just fine. Associated logs:
Renderer: [vscode-debugadapter-42.json.gz](https://github.com/microsoft/vscode-js-debug/files/5276154/vscode-debugadapter-42.json.gz)
Electron Main: [vscode-debugadapter-43.json.gz](https://github.com/microsoft/vscode-js-debug/files/5276164/vscode-debugadapter-43.json.gz)

After further investigation, I narrowed it down to the following: I have configured the `terminal.integrated.cwd` property in my *.code-workspace file (note that I am also setting `cwd` in the electron launch.json, but not the chrome attach launch.json).
1. If `terminal.integrated.cwd` is set to the workspace root path, I observe the bug described above.
2. If I remove the `terminal.integrated.cwd` setting from my workspace file, I still observe the bug (I believe the value I put in the setting was equal to the default value, so doing this probably did not actually change anything).
3. If I enter an invalid path for `terminal.integrated.cwd`, the debug configuration works fine with the new debugger.
4. If I switch back to the old debugger and keep `terminal.integrated.cwd`as it was originally, it works fine too.

Note that for each test case listed above, I closed and reopened VS Code after changing the setting.

Let me know if this is enough to go on, otherwise I will go ahead and try to slim down my reproduction repo to something I can post online.

**Comment by connor4312** [comment]
That's quite interesting. As far as I know `terminal.integrated.cwd` will never be used in this debug pathway, since you don't request that we run the program in an integrated or external terminal. I know that Chrome does tend to surface missing files or mismatched configurations as "access denied"s, but am still not sure how that is getting hit in this scenario. Unfortunately even with this setup I can't seem to hit it locally..

I noticed you have `preLaunchTask`s for both your configurations. My guess would be that the cwd _might_ be affecting something in how those are running.

If you are able to create a slim repro, that would be super helpful to be able to drill down here.

**Comment by s4m0r4m4** [comment]
Ok sorry for the delay. Here's a slim repo where I can't get debug breakpoints to hit for the Renderer/UI nor the Main process: https://github.com/s4m0r4m4/electron-debug-test. Let me know if you need any further info!

**Comment by connor4312** [comment]
Thanks a ton for the repo! I was able to get it running, and actually breakpoints worked out of the box for me in the main process, at least setting them in various methods in `rh-main-app.ts`. One thing I had to do was change the url filter from `http://localhost:4202/*` to `http://localhost:4202`, since `http://localhost:4202` didn't match the former (probably a tweak I should make). But with that change things seemed to work well, am I doing something different than you are?

[Recording](https://memes.peet.io/img/20-10-4bc6dd4f-e4ab-4ef9-86c2-c2d03d71a8cd.mp4)

**Comment by s4m0r4m4** [comment]
Thanks for the recording, that was helpful to see how you were running it. It looks like you perhaps ran ng serve first, then the MAIN debug config, then the UI debug config. 

Here are the exact steps I followed:
1. Open CMD in C:\TEMP
2. git clone https://github.com/s4m0r4m4/electron-debug-test.git
3. Open the VS code workspace file
4. Terminal opens in "C:\TEMP\electron-debug-test\apps\main"
5. cd ..\..
6. npm install
7. Set breakpoints in main.ts and app.component.ts
8. Run debug config "Both"
9. Weep as the electron app blows past both breakpoints without stopping

The only other difference I can think of is my user-specific VS code settings, which obviously are not included in the git repo:
```
{
    "angularConsole.useNVM": false,
    "debug.onTaskErrors": "debugAnyway",
    "editor.fontSize": 16,
    "explorer.confirmDragAndDrop": false,
    "files.associations": {
      "*.json": "jsonc"
    },
    "qub-xml-vscode.telemetry.enabled": false,
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "timeline.excludeSources": [],
    "todo-tree.tree.showScanModeButton": false,
    "window.zoomLevel": 0,
    "workbench.commandPalette.history": 100,
    "workbench.iconTheme": "material-icon-theme",
    "workbench.tree.indent": 20,
    "[typescript]": {
      "editor.defaultFormatter": "vscode.typescript-language-features"
    },
    "[jsonc]": {
      "editor.defaultFormatter": "vscode.json-language-features"
    },
    "editor.largeFileOptimizations": false,
    "git.confirmSync": false
  }
```

**Comment by connor4312** [comment]
Thanks for the clarification, two things:

> Weep again as the electron app blows past the app.component.ts breakpoint without stopping

Attaching the to the electron renderer is asynchronous, and the renderer does not wait for the debugger before it starts the webpage. In the sample, app.component.ts doesn't have any code that's run continously, so if you for example have a breakpoint in the constructor, it will only be hit on reload.

There is not a native mechanism in electron for us to ask that such a pause happens. However, we added the ability to have a manual pause for the VS Code webworker extension host in https://github.com/microsoft/vscode/issues/106698#issuecomment-702846751. If this is a scenario you're interested in we could have the debugger published a similar flag for all browser attachments (I don't think there's any negative side effects of this) which would let you have a similar loop.

> Weep as the electron app blows past the main.ts breakpoint without stopping

It looks like this is specifically code that's run early on in your application. For some reason the URL that "main.js" appears as is

```
file:///E:/Downloads/electron-debug-test/node_modules/electron/dist/resources/default_app.asar/main.js
```

-- inside node_modules, rather than it's correct location on disk. I haven't observed this before and don't know why this is happening here. I'll look into it on Monday.

**Comment by s4m0r4m4** [comment]
Ah I see, thanks for clarifying the behavior with attaching to the electron renderer process. I read through the thread you linked and, while I don't completely understand the inner workings of VS code debugging, if that solution provides the ability for breakpoints to catch in the renderer process on load that would be awesome, I would totally be interested in such a feature.

For the main.js location issue, I am not sure what would be causing that either, I'll wait to hear back on that one.

Thanks for your support on this!

**Comment by s4m0r4m4** [comment]
Sure
