### ISSUE TITLE
Breakpoints stop working when switching to "in-preview" debugger

### ISSUE THREAD

**Issue by theoribeiro** [microsoft/vscode-js-debug#754]
**Describe the bug**
I have a Nuxt application that I am able to debug correctly when I set "debug.javascript.usePreview": false in my settings. However, for some reason the breakpoints get either misplaced or unbound whenever I set the usePreview flag to true. 

Here is my launch.json:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:8090",
      "webRoot": "${workspaceFolder}/src",
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*",
        "webpack:///src/*": "${webRoot}/*",
        "webpack:///*": "*",
        "webpack:///./~/*": "${webRoot}/node_modules/*"
      },
      "trace": true
    }
  ]
}

```

**To Reproduce**
1. Set breakpoint in Nuxt application
2. Start debugging
3. Hit breakpoint
4. Add "debug.javascript.usePreview": true to settings.json
5. Start debugging
6. Don't hit breakpoint (breakpoint unbound or misplaced, depending on the line)

**Log File**

[vscode-debugadapter-0.txt](https://github.com/microsoft/vscode-js-debug/files/5213457/vscode-debugadapter-0.txt)

**VS Code Version:** 1.49.0

**Comment by connor4312** [comment]
In the log you sent, the only breakpoints were set in  `/Users/theoribeiro/Dev/app/services/frontend-admin/test/unit/pages/waitlist.spec.js`, however no files in `test/unit` were loaded by your application. Please collect a log where a breakpoint that you expected to hit is not hit.

**Comment by theoribeiro** [comment]
Thanks for replying @connor4312 .  My mistake, I forgot to set the correct breakpoints before getting the last log. 

Please find the correct log attached. I set a breakpoint on line 260 on waitlist.vue but when ran the debugger stopped on line 40.
[vscode-debugadapter-0.txt](https://github.com/microsoft/vscode-js-debug/files/5214402/vscode-debugadapter-0.txt)

**Comment by connor4312** [comment]
Thank you for the log! This seems to be a case of https://github.com/vuejs/vue/issues/11023. In some setups, Vue does not generate sourcemaps that we can deterministically map back to files on the disk.

**Comment by theoribeiro** [comment]
Thanks, @connor4312, I see the issue and understand the problem could be fixed more easily on the vue side of things. Out of curiosity what is it that made the old javascript debugger work but not the new?

**Comment by connor4312** [comment]
I think the old debugger may worked for _some_ vue apps if they happened to load the 'real' version of the file first, because it didn't support mapping multiple sources back to the same path on disk. I didn't realize this before, maybe that's an additional vue-specific heuristic that we can add, on top of the other vue-specific heuristics.

(Other vue setups do something different, but equally confusing https://github.com/microsoft/vscode-js-debug/commit/2f3c93a08df0ceb09eda86251d0309d34bfb26ef)

However, we now support mapping multiple files in the runtime back to sources--which is more correct, especially when working with web apps where a source may appear in multiple files--but that means that we try placing the breakpoint in those supporting files as well, which causes all sorts of weirdness.

I'll actually reopen this pending investigation on (1). If you're app is open source, it'd be helpful to share it with me so I have something to test against. If not I can try to get a local repro separately.

**Comment by theoribeiro** [comment]
Unfortunately my repo is private. Do you want me to try to set up a repro?

**Comment by connor4312** [comment]
It's fine, I can try to set up a Nuxt app which might be enough to hit will. Will give you a shout if not.

**Comment by connor4312** [comment]
I tried pulling down https://github.com/nuxt/hackernews and hitting breakpoints in components worked fine. It seems that app created sources that matched the heuristic I added in the linked commit.

Something I noticed, though, that in SSR mode we _did_ get some sources of the pages, but not the correct page contents, and it gave me a log very similar to the second one you posted. I couldn't hit breakpoints in that page, which is expected since the page would be evaluated in the server rather than in Chrome.

However, switching to spa mode with `nuxt --spa`, I was able to hit breakpoints in the pages.

Is there any chance you're running into something similar?

**Comment by connor4312** [comment]
Haven't heard anything more -- let me know if this info is useful / whether you're still hitting issues.

**Comment by theoribeiro** [comment]
Hey @connor4312, somehow I ended up missing the notification for this thread. 

I just tried our project with `--spa` only and it is still not hitting the breakpoint if preview is enabled.

**Comment by connor4312** [comment]
Please collect in --spa mode

**Comment by theoribeiro** [comment]
Here it is!
[vscode-debugadapter-0.txt](https://github.com/microsoft/vscode-js-debug/files/5386228/vscode-debugadapter-0.txt)

I agree with you that the breakpoint wouldn't be hit in SSR mode but that would be on page load only and on the `created` hooks. 

All the cases I have been trying are breakpoints that should be hit on the `mounted` hook. And again, they are hit perfectly when I use the old debugger. 

Please let me know if you need any more info!

**Comment by connor4312** [comment]
Thanks for the logs. It looks like the breakpoint is getting bound and hit, but in the wrong location. Are you able to share your repo, a minimal repro, or information about the tools you're using/build setup so that I can try to reproduce this and dig in?

**Comment by theoribeiro** [comment]
Our repo is private but let me try to setup a repo with a minimal repro this week

**Comment by theoribeiro** [comment]
@connor4312 I was able to reproduce the error with the code in this repo https://github.com/theoribeiro/nuxt-debug-test
Let me know if you need any more info!

**Comment by connor4312** [comment]
Looks like you're running into https://github.com/vuejs/vue/issues/11023#issuecomment-657167359, I would encourage you to 👍 the issue. I can look at applying a hack-around for this case. But it's likely to break in the future. Vue should really work on creating sensible sourcemaps...
