### ISSUE TITLE
Chrome keeps crashing during authentication

### ISSUE THREAD

**Issue by xXGoziXx** [microsoft/vscode-js-debug#764]
**Describe the bug**
Whenever I log into a local angular app using the authentication API, Chrome will 100% crash if it was opened via vscode chrome debugger

**To Reproduce**
1. Open up dev tools in Chrome
2. Create a custom login flow and pass form data to the Auth.signIn method
3. Browser will crash. This usually occurs just after JWT values are stored in localStorage

**Expected behavior**
Uhm, for the browser to not crash

**Log File**

**VS Code Version:** 1.49.0

**Additional context**
Adding  "debug.javascript.usePreview": false to settings seems to solve the problem.

**Comment by connor4312** [comment]
This duplicates https://github.com/microsoft/vscode-js-debug/issues/729. The Chrome team has indicated this will be fixed in the next version, and it should work on Chrome Canary (instructions: https://github.com/microsoft/vscode-js-debug/issues/729#issuecomment-683367574). Ref: https://bugs.chromium.org/p/chromium/issues/detail?id=1123329
