### ISSUE TITLE
Flame chart doesn't use charts foreground color

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-js-debug#780]
From https://github.com/microsoft/vscode-js-debug/issues/756

![image](https://user-images.githubusercontent.com/323878/94728488-25e6a080-0315-11eb-9e3c-2953a38e0522.png)

Also - does any token change the gray? I can imagine a theme wanting to customize that.

**Comment by connor4312** [comment]
The chart foreground color is the text color on charts. The base color of the chart is `charts.red`. We don't use the foreground color for the text drawn over the bars, since that foreground color is meant to contrast with the editor background rather than the chart color. Instead, we [adjust the luminance](https://github.com/microsoft/vscode-js-profile-visualizer/blob/ed1d5627af761455f4885b546aaca242811c5530/packages/vscode-js-profile-flame/src/client/webgl/boxes.ts#L182) so that white is always contrasting-enough on the chart background.
