### ISSUE TITLE
Could not load source map when I enable debug.javascript.usePreview

### ISSUE THREAD

**Issue by njzydark** [microsoft/vscode-js-debug#812]
**Describe the bug**

Could not load source map when I enable `debug.javascript.usePreview`, if I disable, all work

**To Reproduce**

I use this project to debug [https://github.com/easy-mock/easy-mock](https://github.com/easy-mock/easy-mock)

This is my config:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach",
      "port": 9229,
      "request": "attach",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "pwa-node",
      "restart": true
    },
  ]
}
```

**Log File**

[vscode-debugadapter-0.json.gz](https://github.com/microsoft/vscode-js-debug/files/5423230/vscode-debugadapter-0.json.gz)

**VS Code Version:** 1.51.0-insider

**Comment by connor4312** [comment]
Indeed -- we get a scriptParsed event that contains a `server-bundle.js` and a `server-bundle.js.map`. We try to look up `${workspaceFolder}/server-bundle.js.map`, but this doesn't exist.

```
{
  "method": "Debugger.scriptParsed",
  "params": {
    "scriptId": "5783",
    "url": "server-bundle.js",
    "startLine": 0,
    "startColumn": 0,
    "endLine": 12598,
    "endColumn": 3,
    "executionContextId": 1,
    "hash": "A0AEEB600505C814F4F605D433C15C697D1F1B61",
    "isLiveEdit": false,
    "sourceMapURL": "server-bundle.js.map",
    "hasSourceURL": false,
    "isModule": false,
    "length": 1307706
  }
}
```

If this is needed for your scenario, I recommend adjusting your build settings/output so that the sourceMapURL points to a locations (e.g. absolute disk path, or path relative to your workspace folder) that exists. The issue you posted doesn't have enough information around how you build/launch your app for me to say what you need to adjust.

The old debugger didn't show warnings like this, so you would not have seen it there.

**Comment by njzydark** [comment]
The old debugger not only didn't show warnings but also work right, I can set breakpoint and view in source file. But when use new debugger, the breakpoint is occur in readonly file.

This is the project webpack config: [https://github.com/easy-mock/easy-mock/blob/dev/build/webpack.base.config.js](https://github.com/easy-mock/easy-mock/blob/dev/build/webpack.base.config.js)

**Comment by connor4312** [comment]
I'm not seeing any issues running your app locally.

![](https://memes.peet.io/img/20-10-35d666f2-810a-410a-ae5e-b92451adb839.png)

Please share a log with a breakpoint set so that I can see what problem you're hitting.

Note that because you're using a deprecated Node version (8) you'll want to set `enableContentValidation: false`.

**Comment by njzydark** [comment]
wow, when set `enableContentValidation: false` , it works. But why I still see the warning that `Could not load source map from server-bundle.js.map
`

**Comment by connor4312** [comment]
Good to hear. I will go ahead and close this, then -- the setting is a known quirk with Node 8.

Most likely something is being loaded, possible from your dependencies., that has a comment like `//# sourceURL=server-bundle.js` (which overwrites its path when loaded from V8 loads it, thus preventing us from seeing it's from node_modules and omitting the warning) and a sourceMapUrl which doesn't exist.

**Comment by njzydark** [comment]
Thank you so much
