### ISSUE TITLE
The debugger is not getting exported const and var elements.

### ISSUE THREAD

**Issue by daniel-oliv** [microsoft/vscode-js-debug#829]
**Describe the bug**
The debugger is not getting exported const and var elements. I mean, it's not possible to watch them in the debugger lateral panel or look their values putting the mouse over them.
Just the non-exported var and const are available to debug. 
Although they are printed in DEBUG CONSOLE and exported function is available too
Thanks for all!!!

**To Reproduce**
1. Download the repository "https://github.com/daniel-oliv/test-debugger".
2. Run npm install.
3. Put a breakpoint in 37th line of the main.ts file with the content: 
    console.log(`
    Put a breakpoint here 
    and try to watch the exported elements, const and var, 
    or put the mouse over than.
    Just the non-exported var and const are available to debug. 
    Although they are printed in DEBUG CONSOLE and exported function is available too
    Thanks for all!`)
4. Run debbuger.

**VS Code Version:** 1.50.1 (user setup)

**Additional context**

That's my enviroment (from the vs code About section):
VS Code Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by connor4312** [comment]
This is because the exported variables [are rewritten](https://www.typescriptlang.org/play?module=1&ssl=25&ssc=35&pln=17&pc=1#code/KYDwDg9gTgLgBAYwgOwM71JWwAmBhFdAQ2XgF44ByASTiIFs65NoZcBCSgWACgXY4ANyJRm4VrgBqIgJZEARgBtgcCjTqMiYrGxxwYECJ168kaeDNLAoyIooLmS5KrQZwAcgHkAKtok5jHmFRSzYbO2koOSUVNVdNDx8-bD0DI24eXn54ADMAV2QEGBkUOHzkAAoASgBvXjg4KGAYPJsXDSZs3DKCopLkDIBfEz5xAQRFIlRUOABZIks4Op4G+sRCGCg8ouhq5YaGmAALGVQAOmJYaoBuNeGVuAB6R7pUAE9CuEuYVDWpj4QXxgIhgezWhygbyW4IaRAA7gt4MdTmc2OgACLAeTyPIAc2sNxhg0QRBgCCOcAq1ig0CqS1WDwO6zQEGUZ2puw5UAuwIQAGsqrdGXB7g1Ra8AfpgBisTj8VAwcKzKhWcAzooILiqWNdA5iKRBTDlar1ZrtTopLIFMpDZklYQTRqtaFrLZ7BsnLamca2U6Ki7wopItEbUKjQ7fWbytVbeGWZGtQADGEABTy8C08iaRD5kFCcCO1hUMJIqUh+ggcARZIpxxUXT0wGU9GApFQABpmeg6Mg9MFOzDoHAwOn9IW4PQIHlUCoIIJrGOSGcYQApadI8fIFAAWgbQhEPb0yozTTowhkkxiFbgOCxeLOcBhAEFFMcp7ja4WoSIVGAolY9EWdEAFEACEAFUAHE4DwTx3AAZU8AAZYDD2SXQekKYpSlOM8FkvZQKwgGFvCOEg+RmHIhzsRR2ETKpwSaFo2k2PJgCFMURnuEZsi7eB6AWZBVDgZBgDhOZBJuIA) when targeting common.js. We currently don't deal with sourcemap renames, follow this issue for updates: https://github.com/microsoft/vscode/issues/12066
