### ISSUE TITLE
Validate our debugger works with Parcel HMR

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode-js-debug#843]
https://parceljs.org/hmr.html

**Comment by connor4312** [comment]
It looks like this is not possible right now because Parcel doesn't provide sourcemaps for hot-replaced modules. This leaves us dead in the water here, there's no workaround we have since we're unable to correlate source locations. I've opened https://github.com/parcel-bundler/parcel/issues/5313, and will reopen this issue if there's anything actionable on our end once resolved.
