### ISSUE TITLE
Support FNM Node Version Manager in Node configuration provider

### ISSUE THREAD

**Issue by gaui** [microsoft/vscode-js-debug#847]
Support FNM Node Version Manager (https://github.com/Schniz/fnm) in Node configuration provider.

The change would be in this method:
https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension/configurationProvider.ts#L222

The location for each `$VERSION` is here: `$HOME/.fnm/node-versions/$VERSION/installation/bin/node`

**Comment by GlenDC** [comment]
Is there interest from the maintainers to officially support this?

**Comment by connor4312** [comment]
PR's welcome :)

**Comment by GlenDC** [comment]
I would be more then happy to contribute:

- Could you provide me how with you would see this to work from an API POV? So that I make sure we're aligned on its implementation?
- Could you give me any pointers you can, as it would be my first contribution to this plugin or any vscode plugin for that matter.

Want to make sure I know what I need to know and that we're aligned prior to me starting on its support. And thanks for the flexibility on your end!

**Comment by connor4312** [comment]
This is currently handled by the [nvmResolver.ts](https://github.com/microsoft/vscode-js-debug/blob/main/src/targets/node/nvmResolver.ts). This could be refactored a little bit since this one class handles nvs and nvm on both Windows and Unix. Adding FNM would be yet another overload of that.

**Comment by GlenDC** [comment]
Great. Will try to make time for it this week, looks like a fun first contribution :)

**Comment by GlenDC** [comment]
Thanks @thales-maciel  for implementing this! My apologies for not holding my promise here. Very happy to see this shipped!!! Thanks all!

**Comment by Byron2016** [comment]
Worked for me: [Debug a nodejs program. (using fnm) #230759](https://github.com/microsoft/vscode/issues/230759)
