### ISSUE TITLE
Top level folder gets truncated when JS Project is not the root folder

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode-js-debug#894]
**Describe the bug**
When the JavaScript project is not at the top level the debugger doesn't match the paths well.

**To Reproduce**
1. Checkout https://github.com/jasonwilliams/nextjs9-typescript-server-vscode-example/tree/monorepo (monorepo branch)
2. Set a breakpoint on line 9 in webapp/pages/index.tsx (on const alfa)
3. run docker-compose up inside of webapp
4. Once that's running start the debugger (launch server (Docker))
5. It won't bind, run "Create diagnostic information..."
6. You should see the matcher has truncated the "webapp" folder

**Screenshot**
In this screenshot `webapp` is lost (on the second bullet point), causing the matcher not to find the file
![image](https://user-images.githubusercontent.com/936006/102121593-1bc83e80-3e3c-11eb-90a2-9b1164b5b7da.png)

**VS Code Version:** 1.53
**Debugger Version** Nightly (v2020.12.917)

**Comment by connor4312** [comment]
Thanks for the issue. This is because the `sourceMapPathOverrides` are applied to the webpack:/// path. The relevant default here is `'webpack://?:*/*': `${cwd}/*`, so the debugger reports that is applied:

> "SourceMap: mapping webpack:///./pages/index.tsx => e:\\Downloads\\nextjs9-typescript-server-vscode-example/./pages/index.tsx, via sourceMapPathOverrides entry - /^webpack:\\/\\/.*?\\/(.*?)$/i"

This bypasses the localRoot/remoteRoot. The solution here is to set the `"cwd": "${workspaceFolder}/webapp"`.

I think it would make sense to default the cwd to the localRoot, if the former is unset and the latter is.

**Comment by jasonwilliams** [comment]
Thanks @connor4312 !
Out of interest, what is cwd usually based off? Where the node executable runs? Or where the script first fired from?

**Comment by connor4312** [comment]
Generally the workspace folder: https://github.com/microsoft/vscode-js-debug/blob/158eabf72a9d21d050a23969cf07cbe989f6cd80/src/ui/configuration/nodeDebugConfigurationResolver.ts#L159
